import math

""" This generic header will autmatically be added to every packet defined below. """
generic_packet_header = [
    ["packetType",  8,      None, "Byte indicating the type of packet"],
    # Destination
    ["toRobotId",   4,      None, "Id of the receiving robot"],
    ["toColor",     1,      None, "Color of the receiving robot / basestation. Yellow = 0, Blue = 1"],
    ["toBC",        1,      None, "Bit indicating this packet has to be broadcasted to all robots"],
    ["toBS",        1,      None, "Bit indicating this packet is meant for the basestation"],
    ["toPC",        1,      None, "Bit indicating this packet is meant for the PC"],
    # Source
    ["fromRobotId", 4,      None, "Id of the transmitting robot"],
    ["fromColor",   1,      None, "Color of the transmitting robot / basestation. Yellow = 0, Blue = 1"],
    ["reserved",    1,      None, "reserved"],
    ["fromBS",      1,      None, "Bit indicating this packet is coming from the basestation"],
    ["fromPC",      1,      None, "Bit indicating this packet is coming from the PC"],

    ["remVersion",  4,      None, "Version of roboteam_embedded_messages"],
    ["messageId",   4,      None, "messageId. Can be used for aligning packets"],
    ["timestamp",  48,      None, "Unix Timestamp in milliseconds"],
    ["payloadSize", 8,      None, "Size of the payload. At most 255 bytes including the generic_packet_header. Keep the 127 byte SX1280 limit in mind"]
]

packets = {
    "REM_Packet" : [],
    "REM_RobotCommand" : [
        # Movement
        ["rho",                16, [0, 30], "Magnitude of movement (m/s)"],
        ["theta",              16, [-math.pi, math.pi], "Direction of movement (radians)"],
        ["yaw",                16, [-math.pi, math.pi], "Absolute facing angle (rad)"],
        ["angularVelocity",    16, [-10*math.pi, 10*math.pi], "Angular velocity (rad/s)"],
        ["cameraYaw",          16, [-math.pi, math.pi], "Angle of the robot as seen by camera (rad)"],
        ["acceleration_magnitude", 16, [-15, 15], "Magnitude of acceleration (m/s^2)"],
        ["acceleration_angle", 16, [-math.pi, math.pi], "Angle of acceleration (rad)"],
        # Kicker / Chipper
        ["kickChipPower",       8,  [0, 8.0], "Speed of the ball in m/s"],
        ["doKick",              1,  None, "Do a kick if ballsensor"],
        ["doChip",              1,  None, "Do a chip if ballsensor"],
        ["kickAtYaw",           1,  None, "Do a kick once yaw is reached"],
        ["doForce",             1,  None, "Do regardless of ballsensor"],
        # Yaw
        ["useCameraYaw",        1,  None, "Use the info in 'cameraYaw'"],
        ["useYaw",              1,  None, "0 = angular velocity, 1 = yaw"],
        # Dribbler
        ["dribblerOn",          1,  None, "Dribbler on/off"],
        ["dribblerOption1",     1,  None, "Dribbler option 1"],
        ["dribblerOption2",     1,  None, "Dribbler option 2"],
        ["dribblerOption3",     1,  None, "Dribbler option 3"],
        ["dribblerOption4",     1,  None, "Dribbler option 4"],
        ["dribblerOption5",     1,  None, "Dribbler option 5"],
        ["dribblerOption6",     1,  None, "Dribbler option 6"],
        # Other
        ["sendStateInfo",       1,  None, "Indicate if stateInfo should be send back"],
        ["wheelsOff",           1,  None, "Indicate that the robot should stop moving"],
        ["reboot",              1,  None, "Reboot the robot remotely"],        
    ],
    "REM_RobotCommandTesting" : [
        # Movement
        ["rho",                 16, [0, 30], "Magnitude of movement (m/s)"],
        ["theta",               16, [-math.pi, math.pi], "Direction of movement (radians)"],
        ["yaw",                 16, [-math.pi, math.pi], "Absolute angle (rad)"],
        ["angularVelocity",     16, [-10*math.pi, 10*math.pi], "Angular velocity (rad/s)"],
        ["cameraYaw",           16, [-math.pi, math.pi], "Angle of the robot as seen by camera (rad)"],
        ["wheelSpeedRef1",      16, [-1000, 1000] , "Bypass the body control loop and directly set the refernce of wheel 1"],
        ["wheelSpeedRef2",      16, [-1000, 1000] , "Bypass the body control loop and directly set the refernce of wheel 2"],
        ["wheelSpeedRef3",      16, [-1000, 1000] , "Bypass the body control loop and directly set the refernce of wheel 3"],
        ["wheelSpeedRef4",      16, [-1000, 1000] , "Bypass the body control loop and directly set the refernce of wheel 4"],
        ["wheelPWM1",           16, [-1, 1]       , "Bypass the body and wheel control loops and directly set the PWM input of wheel 1"],
        ["wheelPWM2",           16, [-1, 1]       , "Bypass the body and wheel control loops and directly set the PWM input of wheel 2"],
        ["wheelPWM3",           16, [-1, 1]       , "Bypass the body and wheel control loops and directly set the PWM input of wheel 3"],
        ["wheelPWM4",           16, [-1, 1]       , "Bypass the body and wheel control loops and directly set the PWM input of wheel 4"],
        ["useWheelSpeedRef",    1,  None, "If set to 1 use the wheelSpeedRefX, if set to 0 use the rho/theta/angle/angular velocity"],
        ["useWheelPWMRef",      1,  None, "If set to 1 use the wheelPWMRefX, if set to 0 use the rho/theta/angle/angular velocity"],
        # Kicker / Chipper
        ["doKick",              1,  None, "Do a kick if ballsensor"],
        ["doChip",              1,  None, "Do a chip if ballsensor"],
        ["kickAtAngle",         1,  None, "Do a kick once angle is reached"],
        ["doForce",             1,  None, "Do regardless of ballsensor"],
        ["wheelsOff",           1,  None, "Indicate that the robot should stop moving"],
        ["feedback",            1,  None, "Ignore the packet. Just send feedback"],
        ["kickChipPower",       8,  [0, 8.0], "Speed of the ball in m/s"],
        ["reboot",              1,  None, "Reboot the robot remotely"],        
        # Angle
        ["useCameraYaw",        1,  None, "Use the info in 'cameraYaw'"],
        ["useAbsoluteYaw",      1,  None, "0 = angular velocity, 1 = absolute yaw"],
        ["unused",              5,  None, "Unused bits"],
        # Dribbler
        ["dribblerOn",          1,  None, "Dribbler on/off"],
        ["dribblerOption1",     1,  None, "Dribbler option 1"],
        ["dribblerOption2",     1,  None, "Dribbler option 2"],
        ["dribblerOption3",     1,  None, "Dribbler option 3"],
        ["dribblerOption4",     1,  None, "Dribbler option 4"],
        ["dribblerOption5",     1,  None, "Dribbler option 5"],
        ["dribblerOption6",     1,  None, "Dribbler option 6"],
        ["sendStateInfo",       1,  None, "Indicate if stateInfo should be send back"],
    ],
    "REM_RobotFeedback" : [
        # Movement
        ["rho",                 16, [0, 30],                "The estimated magnitude of movement (m/s)"],
        ["theta",               16, [-math.pi, math.pi],    "The estimated direction of movement (rad)"],
        ["yaw",                 16, [-math.pi, math.pi],    "The estimated angle (rad)"],
        
        ["batteryLevel",        16,  [15, 30],    "The voltage level of the battery"],
        ["XsensCalibrated",     1,  None,       "Indicates if the XSens IMU is calibrated"],
        # Ball handling
        ["ballSensorWorking",   1,  None, "Indicates if the ballsensor is working"],
        ["ballSensorSeesBall",  1,  None, "Indicates if the ballsensor sees the ball"],
        ["dribblerSeesBall",    1,  None, "Indicates if the dribbler sees the ball"],
        # Kicker
        ["kickerFault",         1,  None, "Indicates if the kicker sends back a fault"],
        ["kickerOn",            1,  None, "Indicates if the kicker is on"],
        ["capacitorCharged",    1,  None, "Indicates if the capacitor for kicking and chipping is charged"],
        ["reserved1",           1,  None, "reserved1"],    
        ["kickerVoltage",       10, None, "Capacitor voltage"],
        ["filler",              54, None, "filler bits to have equal or more bytes than REM_RobotCommand"]
    ],
    "REM_ControlDebug" : [
        ["xsensAcc1",          16, [-100, 100],         "X component of the acceleration as determined by the IMU [m/s^2]"],
        ["xsensAcc2",          16, [-100, 100],         "Y component of the acceleration as determined by the IMU [m/s^2]"],
        ["xsensYaw",           32, [-50000., 50000.],   "Yaw as determined by the IMU [rad]"],
        ["rateOfTurn",         16, [-20., 20.],         "Turn rate of the robot [rad/s]"],
        ["wheelSpeed1",        16, [-1000., 1000.],     "Speed of wheel 1 as determined by the encoder [rad/s]"],
        ["wheelSpeed2",        16, [-1000., 1000.],     "Speed of wheel 2 as determined by the encoder [rad/s]"],
        ["wheelSpeed3",        16, [-1000., 1000.],     "Speed of wheel 3 as determined by the encoder [rad/s]"],
        ["wheelSpeed4",        16, [-1000., 1000.],     "Speed of wheel 4 as determined by the encoder [rad/s]"],
        ["Debug0",             21, [-1000, 1000],       "Debug port 0"],
        ["Debug1",             21, [-1000, 1000],       "Debug port 1"],
        ["Debug2",             21, [-1000, 1000],       "Debug port 2"],
        ["Debug3",             21, [-1000, 1000],       "Debug port 3"],
        ["Debug4",             21, [-1000, 1000],       "Debug port 4"],
        ["Debug5",             21, [-1000, 1000],       "Debug port 5"],
        ["Debug6",             21, [-1000, 1000],       "Debug port 6"],
        ["Debug7",             21, [-1000, 1000],       "Debug port 7"],
        ["Debug8",             21, [-1000, 1000],       "Debug port 8"],
        ["Debug9",             21, [-1000, 1000],       "Debug port 9"],
        ["Debug10",            21, [-1000, 1000],       "Debug port 10"],
        ["Debug11",            21, [-1000, 1000],       "Debug port 11"],
        ["Debug12",            21, [-1000, 1000],       "Debug port 12"],
        ["Debug13",            21, [-1000, 1000],       "Debug port 13"],
        ["Debug14",            21, [-1000, 1000],       "Debug port 14"],
        ["Debug15",            21, [-1000, 1000],       "Debug port 15"],
        ["Debug16",            21, [-1000, 1000],       "Debug port 16"],
        ["Debug17",            21, [-1000, 1000],       "Debug port 17"],
        ["Debug18",            21, [-1000, 1000],       "Debug port 18"],
        ["Debug19",            21, [-1000, 1000],       "Debug port 19"],
        ["Debug20",            21, [-1000, 1000],       "Debug port 20"],
        ["Debug21",            21, [-1000, 1000],       "Debug port 21"],
        ["Debug22",            21, [-1000, 1000],       "Debug port 22"],
        ["Debug23",            21, [-1000, 1000],       "Debug port 23"],
        ["Debug24",            21, [-1000, 1000],       "Debug port 24"],
        ["Debug25",            21, [-1000, 1000],       "Debug port 25"],
        ["Debug27",            21, [-1000, 1000],       "Debug port 27"],
        ["Debug28",            21, [-1000, 1000],       "Debug port 28"],
        ["Debug29",            21, [-1000, 1000],       "Debug port 29"],
        ["Debug26",            21, [-1000, 1000],       "Debug port 26"],
        ["Debug30",            21, [-1000, 1000],       "Debug port 30"],
        ["Debug31",            21, [-1000, 1000],       "Debug port 31"],
    ],
    "REM_RobotStateInfo" : [
        ["xsensAcc1",          16, [-100, 100], "xsensAcc1"],
        ["xsensAcc2",          16, [-100, 100], "xsensAcc2"],
        ["xsensYaw",           32, [-50000., 50000.], "xsensYaw"],
        ["rateOfTurn",         16, [-20., 20.], "rateOfTurn"],
        ["wheelSpeed1",        16, [-1000., 1000.], "wheelSpeed1"],
        ["wheelSpeed2",        16, [-1000., 1000.], "wheelSpeed2"],
        ["wheelSpeed3",        16, [-1000., 1000.], "wheelSpeed3"],
        ["wheelSpeed4",        16, [-1000., 1000.], "wheelSpeed4"],
        ["dribbleSpeed",       16, [0.     , 5000.], "dribblerSpeed"],
        ["filteredDribbleSpeed",	16, [0.     , 5000.], "filtered dribblerSpeed"],
        ["dribblespeedBeforeGotBall",	16, [0.     , 5000.], "dribblerSpeed at at the time dribbler thinks it got the ball"],
        ["bodyXIntegral",      	16, [-200., 200.], "Integral value from the PID for body_x"],
        ["bodyYIntegral", 		16, [-200., 200.], "Integral value from the PID for body_y"],
        ["bodyWIntegral", 		16, [-200., 200.], "Integral value from the PID for body_w"],
        ["bodyYawIntegral",		16, [-10., 10.], "Integral value from the PID for body_Yaw"],
        ["wheel1Integral",     	16, [-1000., 1000.], "Integral value from the PID for Wheel_1"],
        ["wheel2Integral",    	16, [-1000., 1000.], "Integral value from the PID for Wheel_2"],
        ["wheel3Integral",   	16, [-1000., 1000.], "Integral value from the PID for Wheel_3"],
        ["wheel4Integral",  	16, [-1000., 1000.], "Integral value from the PID for Wheel_4"],
        ["wheelSpeedRef1",      16, [-1000.,1000.], "Reference speed of Wheel_1"],
        ["wheelSpeedRef2",      16, [-1000.,1000.], "Reference speed of Wheel_2"],
        ["wheelSpeedRef3",      16, [-1000.,1000.], "Reference speed of Wheel_3"],
        ["wheelSpeedRef4",      16, [-1000.,1000.], "Reference speed of Wheel_4"],
        ["wheelController_1",   16, [-1, 1],        "Wheel_1 controller output"],
        ["wheelController_2",   16, [-1, 1],        "Wheel_2 controller output"],
        ["wheelController_3",   16, [-1, 1],        "Wheel_3 controller output"],
        ["wheelController_4",   16, [-1, 1],        "Wheel_4 controller output"],
        ["bodyController_u",    16, [-100, 100],    "Body u controller output"],
        ["bodyController_v",    16, [-100, 100],    "Body v controller output"],
        ["bodyController_w",    16, [-100, 100],    "Body w controller output"],
        ["bodyController_yaw",    16, [-100, 100],    "Body yaw controller output"],
        ["bodyControllerRef_u", 16, [-100, 100],    "Reference speed body velocity u"],
        ["bodyControllerRef_v", 16, [-100, 100],    "Reference speed body velocity v"],
        ["bodyControllerRef_w", 16, [-100, 100],    "Reference speed body velocity w"],
        ["bodyControllerRef_yaw", 16, [-100, 100],    "Reference speed body velocity yaw"],
        ["wheelSpeedDerivativeFiltered1", 16, [-1000, 1000], "Filtered derivative value for the PID for wheel_1"],
        ["wheelSpeedDerivativeFiltered2", 16, [-1000, 1000], "Filtered derivative value for the PID for wheel_2"],
        ["wheelSpeedDerivativeFiltered3", 16, [-1000, 1000], "Filtered derivative value for the PID for wheel_3"],
        ["wheelSpeedDerivativeFiltered4", 16, [-1000, 1000], "Filtered derivative value for the PID for wheel_4"],
        ["bodyXDerivativeFiltered",       16, [-100, 100],   "Filtered derivative for the PID for body_x"],
        ["bodyYDerivativeFiltered",       16, [-100, 100],   "Filtered derivative for the PID for body_y"],
        ["bodyZDerivativeFiltered",       16, [-100, 100],   "Filtered derivative for the PID for body_z"],
        ["bodyYawDerivativeFiltered",     16, [-100, 100],   "Filtered derivative for the PID for body_yaw"],

    ],
    "REM_RobotBuzzer" : [
    	["period",             12, None, "Sound that the buzzer makes."],
    	["duration",           16, [0., 5.], "Duration of the sound"]
    ],
    "REM_Log"                         : [],
    "REM_BasestationGetConfiguration" : [],
    "REM_BasestationConfiguration"    : [
        ["channel",             1, None, "Channel on which the basestation and robots communicate"]
    ],
    "REM_RobotGetPIDGains"            : [],
    "REM_RobotPIDGains" : [
        ["PbodyX",             16, [0.,100.], "Received P gain of the PID for body_x (x-direction)"],
        ["IbodyX",             16, [0.,100.], "Received I gain of the PID for body_x (x-direction)"],
        ["DbodyX",             16, [0.,100.], "Received D gain of the PID for body_x (x-direction)"],
        ["DbodyX2",            16, [0.,100.], "Received second D gain of the PID for body_x (x-direction)"],
        ["PbodyY",             16, [0.,100.], "Received P gain of the PID for body_y (y-direction)"],
        ["IbodyY",             16, [0.,100.], "Received I gain of the PID for body_y (y-direction)"],
        ["DbodyY",             16, [0.,100.], "Received D gain of the PID for body_y (y-direction)"],
        ["DbodyY2",            16, [0.,100.], "Received second D gain of the PID for body_y (y-direction)"],
        ["PbodyW",             16, [0.,100.], "Received P gain of the PID for body_w (Angular velocity)"],
        ["IbodyW",             16, [0.,100.], "Received I gain of the PID for body_w (Angular velocity)"],
        ["DbodyW",             16, [0.,100.], "Received D gain of the PID for body_w (Angular velocity)"],
        ["DbodyW2",            16, [0.,100.], "Received second D gain of the PID for body_w (w-direction)"],
        ["PbodyYaw",           16, [0.,100.], "Received P gain of the PID for body_yaw (Absolute angle)"],
        ["IbodyYaw",           16, [0.,100.], "Received I gain of the PID for body_yaw (Absolute angle)"],
        ["DbodyYaw",           16, [0.,100.], "Received D gain of the PID for body_yaw (Absolute angle)"],
        ["DbodyYaw2",          16, [0.,100.], "Received second D gain of the PID for body_taw (Absolute angle)"],
        ["Pwheels",            16, [0.,100.], "Received P gain of the PID for the wheels"],
        ["Iwheels",            16, [0.,100.], "Received I gain of the PID for the wheels"],
        ["Dwheels",            16, [0.,100.], "Received D gain of the PID for the wheels"]
    ],
    "REM_RobotSetPIDGains" : [
        ["PbodyX",             16, [0.,100.], "Commanded P gain of the PID for body_x (x-direction)"],
        ["IbodyX",             16, [0.,100.], "Commanded I gain of the PID for body_x (x-direction)"],
        ["DbodyX",             16, [0.,100.], "Commanded D gain of the PID for body_x (x-direction)"],
        ["DbodyX2",            16, [0.,100.], "Commanded second D gain of the PID for body_x (x-direction)"],
        ["PbodyY",             16, [0.,100.], "Commanded P gain of the PID for body_y (y-direction)"],
        ["IbodyY",             16, [0.,100.], "Commanded I gain of the PID for body_y (y-direction)"],
        ["DbodyY",             16, [0.,100.], "Commanded D gain of the PID for body_y (y-direction)"],
        ["DbodyY2",            16, [0.,100.], "Commanded second D gain of the PID for body_y (y-direction)"],
        ["PbodyW",             16, [0.,100.], "Commanded P gain of the PID for body_w (Angular velocity)"],
        ["IbodyW",             16, [0.,100.], "Commanded I gain of the PID for body_w (Angular velocity)"],
        ["DbodyW",             16, [0.,100.], "Commanded D gain of the PID for body_w (Angular velocity)"],
        ["DbodyW2",            16, [0.,100.], "Commanded second D gain of the PID for body_w (w-direction)"],
        ["PbodyYaw",           16, [0.,100.], "Commanded P gain of the PID for body_yaw (Absolute angle)"],
        ["IbodyYaw",           16, [0.,100.], "Commanded I gain of the PID for body_yaw (Absolute angle)"],
        ["DbodyYaw",           16, [0.,100.], "Commanded D gain of the PID for body_yaw (Absolute angle)"],
        ["DbodyYaw2",          16, [0.,100.], "Commanded second D gain of the PID for body_taw (Absolute angle)"],
        ["Pwheels",            16, [0.,100.], "Commanded P gain of the PID for the wheels"],
        ["Iwheels",            16, [0.,100.], "Commanded I gain of the PID for the wheels"],
        ["Dwheels",            16, [0.,100.], "Commanded D gain of the PID for the wheels"],
        ["boolean1",            1, None,      "Undefined functionality"],
        ["boolean2",            1, None,      "Undefined functionality"],
        ["boolean3",            1, None,      "Undefined functionality"],
        ["boolean4",            1, None,      "Undefined functionality"],
        ["boolean5",            1, None,      "Undefined functionality"],
        ["boolean6",            1, None,      "Undefined functionality"],
        ["boolean7",            1, None,      "Undefined functionality"],
        ["boolean8",            1, None,      "Undefined functionality"],
        ["boolean9",            1, None,      "Undefined functionality"],
        ["boolean10",            1, None,      "Undefined functionality"],
        ["boolean11",            1, None,      "Undefined functionality"],
        ["boolean12",            1, None,      "Undefined functionality"],
        ["boolean13",            1, None,      "Undefined functionality"],
        ["boolean14",            1, None,      "Undefined functionality"],
        ["boolean15",            1, None,      "Undefined functionality"],
        ["boolean16",            1, None,      "Undefined functionality"],
        ["unlabel1",            16, [-1000,100],      "Undefined variable"],
        ["unlabel2",            16, [-1000,100],      "Undefined variable"],
        ["unlabel3",            16, [-1000,100],      "Undefined variable"],
        ["unlabel4",            16, [-1000,100],      "Undefined variable"],
        ["unlabel5",            16, [-1000,100],      "Undefined variable"],
        ["unlabel6",            16, [-1000,100],      "Undefined variable"],
        ["unlabel7",            16, [-1000,100],      "Undefined variable"],
        ["unlabel8",            16, [-1000,100],      "Undefined variable"],
    ],
    "REM_RobotAssuredPacket" : [
        ["sequenceNumber",      8, None, "Number to match this packet with AssuredAck"],
        ["messageLength",       8, None, "Length of the following message"]
    ],
    "REM_RobotAssuredAck" : [
        ["sequenceNumber",      8, None, "Number to match this packet with AssuredPacket"],
    ],
    
    "REM_RobotMusicCommand" : [
        ["play",                1,  None, "Set to play the current song"],
        ["pause",               1,  None, "Set to pause the current song"],
        ["stop",                1,  None, "Set to stop the current song"],

        ["previousSong",        1,  None, "Set to stop the current song"],        
        ["nextSong",            1,  None, "Set to stop the current song"],        

        ["volume",              5,  None, "Set the volume. Value between 1 and 31. 0 is ignored"],
        ["volumeUp",            1,  None, "Set to increase the volume"],
        ["volumeDown",          1,  None, "Set to decrease the volume"],
        
        ["folderId",            4,  None, "The id of the folder, from which to pick a song"],
        ["songId",              8,  None, "Id of the song, given the folder"],
    ],
    # https://media.digikey.com/pdf/Data%20Sheets/Semtech%20PDFs/SX1280-81_Rev3.2_Mar2020.pdf see page 124. 
    # Minimum payload length is 6 bytes
    "REM_SX1280Filler" : [
        ["header",       8,  None, "Header byte indicating the type of packet"],
        ["remVersion",   4,  None, "Version of roboteam_embedded_messages"],
        ["fillerBits",  36,  None, "SX1280 requires a minimum of 6 bytes payload. See documentation page 124."]
    ],
    "REM_RobotKillCommand": [],
}

# For each packet, insert 1 header byte to ensure that it's present
# header_field = ["header", 8, None, "Header byte indicating the type of packet"]
# for packet_name in packets:
#     packets[packet_name] = [header_field] + packets[packet_name]

# For each packet, add the generic_header_packet
for packet_name in packets:
    if packet_name == "REM_SX1280Filler": continue
    packets[packet_name] = generic_packet_header + packets[packet_name]

