# AUTOGENERATED. Run generator/main.py to regenerate
"""
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- packetType
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toRobotId
-------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toColor
-------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBC
-------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBS
-------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toPC
-------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromRobotId
-------- -------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromColor
-------- -------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- reserved
-------- -------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromBS
-------- -------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromPC
-------- -------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- remVersion
-------- -------- -------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- messageId
-------- -------- -------- -------- 11111111 11111111 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- timestamp
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- payloadSize
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- targetX
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- targetY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- yaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- cameraYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- kickChipPower
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 1------- -------- doKick
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -1------ -------- doChip
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- --1----- -------- kickAtYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ---1---- -------- doForce
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1--- -------- useCameraYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -----1-- -------- useYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ------1- -------- dribblerOn
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------1 -------- dribblerOption1
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 1------- dribblerOption2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -1------ dribblerOption3
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- --1----- dribblerOption4
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ---1---- dribblerOption5
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1--- dribblerOption6
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -----1-- sendStateInfo
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ------1- wheelsOff
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------1 reboot
"""

import numpy as np
from . import REM_BaseTypes



class REM_RobotCommand:
    packetType = 0            # integer [0, 255]             Byte indicating the type of packet
    toRobotId = 0             # integer [0, 15]              Id of the receiving robot
    toColor = 0               # integer [0, 1]               Color of the receiving robot / basestation. Yellow = 0, Blue = 1
    toBC = 0                  # integer [0, 1]               Bit indicating this packet has to be broadcasted to all robots
    toBS = 0                  # integer [0, 1]               Bit indicating this packet is meant for the basestation
    toPC = 0                  # integer [0, 1]               Bit indicating this packet is meant for the PC
    fromRobotId = 0           # integer [0, 15]              Id of the transmitting robot
    fromColor = 0             # integer [0, 1]               Color of the transmitting robot / basestation. Yellow = 0, Blue = 1
    reserved = 0              # integer [0, 1]               reserved
    fromBS = 0                # integer [0, 1]               Bit indicating this packet is coming from the basestation
    fromPC = 0                # integer [0, 1]               Bit indicating this packet is coming from the PC
    remVersion = 0            # integer [0, 15]              Version of roboteam_embedded_messages
    messageId = 0             # integer [0, 15]              messageId. Can be used for aligning packets
    timestamp = 0             # integer [0, 281474976710655] Unix Timestamp in milliseconds
    payloadSize = 0           # integer [0, 255]             Size of the payload. At most 255 bytes including the generic_packet_header. Keep the 127 byte SX1280 limit in mind
    targetX = 0               # float   [0.000, 4.000]       X coordinate to reach
    targetY = 0               # float   [0.000, 6.000]       Y coordinate to reach
    yaw = 0                   # float   [-3.142, 3.142]      Absolute facing angle (rad)
    cameraYaw = 0             # float   [-3.142, 3.142]      Angle of the robot as seen by camera (rad)
    kickChipPower = 0         # float   [0.000, 8.000]       Speed of the ball in m/s
    doKick = 0                # integer [0, 1]               Do a kick if ballsensor
    doChip = 0                # integer [0, 1]               Do a chip if ballsensor
    kickAtYaw = 0             # integer [0, 1]               Do a kick once yaw is reached
    doForce = 0               # integer [0, 1]               Do regardless of ballsensor
    useCameraYaw = 0          # integer [0, 1]               Use the info in 'cameraYaw'
    useYaw = 0                # integer [0, 1]               0 = angular velocity, 1 = yaw
    dribblerOn = 0            # integer [0, 1]               Dribbler on/off
    dribblerOption1 = 0       # integer [0, 1]               Dribbler option 1
    dribblerOption2 = 0       # integer [0, 1]               Dribbler option 2
    dribblerOption3 = 0       # integer [0, 1]               Dribbler option 3
    dribblerOption4 = 0       # integer [0, 1]               Dribbler option 4
    dribblerOption5 = 0       # integer [0, 1]               Dribbler option 5
    dribblerOption6 = 0       # integer [0, 1]               Dribbler option 6
    sendStateInfo = 0         # integer [0, 1]               Indicate if stateInfo should be send back
    wheelsOff = 0             # integer [0, 1]               Indicate that the robot should stop moving
    reboot = 0                # integer [0, 1]               Reboot the robot remotely



# ================================ GETTERS ================================
    @staticmethod
    def get_packetType(payload):
        return ((payload[0]));

    @staticmethod
    def get_toRobotId(payload):
        return ((payload[1] & 0b11110000) >> 4);

    @staticmethod
    def get_toColor(payload):
        return (payload[1] & 0b00001000) > 0;

    @staticmethod
    def get_toBC(payload):
        return (payload[1] & 0b00000100) > 0;

    @staticmethod
    def get_toBS(payload):
        return (payload[1] & 0b00000010) > 0;

    @staticmethod
    def get_toPC(payload):
        return (payload[1] & 0b00000001) > 0;

    @staticmethod
    def get_fromRobotId(payload):
        return ((payload[2] & 0b11110000) >> 4);

    @staticmethod
    def get_fromColor(payload):
        return (payload[2] & 0b00001000) > 0;

    @staticmethod
    def get_reserved(payload):
        return (payload[2] & 0b00000100) > 0;

    @staticmethod
    def get_fromBS(payload):
        return (payload[2] & 0b00000010) > 0;

    @staticmethod
    def get_fromPC(payload):
        return (payload[2] & 0b00000001) > 0;

    @staticmethod
    def get_remVersion(payload):
        return ((payload[3] & 0b11110000) >> 4);

    @staticmethod
    def get_messageId(payload):
        return ((payload[3] & 0b00001111));

    @staticmethod
    def get_timestamp(payload):
        return ((payload[4]) << 40) | ((payload[5]) << 32) | ((payload[6]) << 24) | ((payload[7]) << 16) | ((payload[8]) << 8) | ((payload[9]));

    @staticmethod
    def get_payloadSize(payload):
        return ((payload[10]));

    @staticmethod
    def get_targetX(payload):
        _targetX = ((payload[11]) << 8) | ((payload[12]));
        return (_targetX * 0.0000610360875868);

    @staticmethod
    def get_targetY(payload):
        _targetY = ((payload[13]) << 8) | ((payload[14]));
        return (_targetY * 0.0000915541313802);

    @staticmethod
    def get_yaw(payload):
        _yaw = ((payload[15]) << 8) | ((payload[16]));
        return (_yaw * 0.0000958752621833) + -3.1415926535897931;

    @staticmethod
    def get_cameraYaw(payload):
        _cameraYaw = ((payload[17]) << 8) | ((payload[18]));
        return (_cameraYaw * 0.0000958752621833) + -3.1415926535897931;

    @staticmethod
    def get_kickChipPower(payload):
        _kickChipPower = ((payload[19]));
        return (_kickChipPower * 0.0313725490196078);

    @staticmethod
    def get_doKick(payload):
        return (payload[20] & 0b10000000) > 0;

    @staticmethod
    def get_doChip(payload):
        return (payload[20] & 0b01000000) > 0;

    @staticmethod
    def get_kickAtYaw(payload):
        return (payload[20] & 0b00100000) > 0;

    @staticmethod
    def get_doForce(payload):
        return (payload[20] & 0b00010000) > 0;

    @staticmethod
    def get_useCameraYaw(payload):
        return (payload[20] & 0b00001000) > 0;

    @staticmethod
    def get_useYaw(payload):
        return (payload[20] & 0b00000100) > 0;

    @staticmethod
    def get_dribblerOn(payload):
        return (payload[20] & 0b00000010) > 0;

    @staticmethod
    def get_dribblerOption1(payload):
        return (payload[20] & 0b00000001) > 0;

    @staticmethod
    def get_dribblerOption2(payload):
        return (payload[21] & 0b10000000) > 0;

    @staticmethod
    def get_dribblerOption3(payload):
        return (payload[21] & 0b01000000) > 0;

    @staticmethod
    def get_dribblerOption4(payload):
        return (payload[21] & 0b00100000) > 0;

    @staticmethod
    def get_dribblerOption5(payload):
        return (payload[21] & 0b00010000) > 0;

    @staticmethod
    def get_dribblerOption6(payload):
        return (payload[21] & 0b00001000) > 0;

    @staticmethod
    def get_sendStateInfo(payload):
        return (payload[21] & 0b00000100) > 0;

    @staticmethod
    def get_wheelsOff(payload):
        return (payload[21] & 0b00000010) > 0;

    @staticmethod
    def get_reboot(payload):
        return (payload[21] & 0b00000001) > 0;

# ================================ SETTERS ================================
    @staticmethod
    def set_packetType(payload, packetType):
        payload[0] = packetType;

    @staticmethod
    def set_toRobotId(payload, toRobotId):
        payload[1] = ((toRobotId << 4) & 0b11110000) | (payload[1] & 0b00001111);

    @staticmethod
    def set_toColor(payload, toColor):
        payload[1] = ((toColor << 3) & 0b00001000) | (payload[1] & 0b11110111);

    @staticmethod
    def set_toBC(payload, toBC):
        payload[1] = ((toBC << 2) & 0b00000100) | (payload[1] & 0b11111011);

    @staticmethod
    def set_toBS(payload, toBS):
        payload[1] = ((toBS << 1) & 0b00000010) | (payload[1] & 0b11111101);

    @staticmethod
    def set_toPC(payload, toPC):
        payload[1] = (toPC & 0b00000001) | (payload[1] & 0b11111110);

    @staticmethod
    def set_fromRobotId(payload, fromRobotId):
        payload[2] = ((fromRobotId << 4) & 0b11110000) | (payload[2] & 0b00001111);

    @staticmethod
    def set_fromColor(payload, fromColor):
        payload[2] = ((fromColor << 3) & 0b00001000) | (payload[2] & 0b11110111);

    @staticmethod
    def set_reserved(payload, reserved):
        payload[2] = ((reserved << 2) & 0b00000100) | (payload[2] & 0b11111011);

    @staticmethod
    def set_fromBS(payload, fromBS):
        payload[2] = ((fromBS << 1) & 0b00000010) | (payload[2] & 0b11111101);

    @staticmethod
    def set_fromPC(payload, fromPC):
        payload[2] = (fromPC & 0b00000001) | (payload[2] & 0b11111110);

    @staticmethod
    def set_remVersion(payload, remVersion):
        payload[3] = ((remVersion << 4) & 0b11110000) | (payload[3] & 0b00001111);

    @staticmethod
    def set_messageId(payload, messageId):
        payload[3] = (messageId & 0b00001111) | (payload[3] & 0b11110000);

    @staticmethod
    def set_timestamp(payload, timestamp):
        payload[4] = (timestamp >> 40);
        payload[5] = (timestamp >> 32);
        payload[6] = (timestamp >> 24);
        payload[7] = (timestamp >> 16);
        payload[8] = (timestamp >> 8);
        payload[9] = timestamp;

    @staticmethod
    def set_payloadSize(payload, payloadSize):
        payload[10] = payloadSize;

    @staticmethod
    def set_targetX(payload, targetX):
        _targetX = int(targetX / 0.0000610360875868);
        payload[11] = (_targetX >> 8);
        payload[12] = _targetX;

    @staticmethod
    def set_targetY(payload, targetY):
        _targetY = int(targetY / 0.0000915541313802);
        payload[13] = (_targetY >> 8);
        payload[14] = _targetY;

    @staticmethod
    def set_yaw(payload, yaw):
        _yaw = int((yaw +3.1415926535897931) / 0.0000958752621833);
        payload[15] = (_yaw >> 8);
        payload[16] = _yaw;

    @staticmethod
    def set_cameraYaw(payload, cameraYaw):
        _cameraYaw = int((cameraYaw +3.1415926535897931) / 0.0000958752621833);
        payload[17] = (_cameraYaw >> 8);
        payload[18] = _cameraYaw;

    @staticmethod
    def set_kickChipPower(payload, kickChipPower):
        _kickChipPower = int(kickChipPower / 0.0313725490196078);
        payload[19] = _kickChipPower;

    @staticmethod
    def set_doKick(payload, doKick):
        payload[20] = ((doKick << 7) & 0b10000000) | (payload[20] & 0b01111111);

    @staticmethod
    def set_doChip(payload, doChip):
        payload[20] = ((doChip << 6) & 0b01000000) | (payload[20] & 0b10111111);

    @staticmethod
    def set_kickAtYaw(payload, kickAtYaw):
        payload[20] = ((kickAtYaw << 5) & 0b00100000) | (payload[20] & 0b11011111);

    @staticmethod
    def set_doForce(payload, doForce):
        payload[20] = ((doForce << 4) & 0b00010000) | (payload[20] & 0b11101111);

    @staticmethod
    def set_useCameraYaw(payload, useCameraYaw):
        payload[20] = ((useCameraYaw << 3) & 0b00001000) | (payload[20] & 0b11110111);

    @staticmethod
    def set_useYaw(payload, useYaw):
        payload[20] = ((useYaw << 2) & 0b00000100) | (payload[20] & 0b11111011);

    @staticmethod
    def set_dribblerOn(payload, dribblerOn):
        payload[20] = ((dribblerOn << 1) & 0b00000010) | (payload[20] & 0b11111101);

    @staticmethod
    def set_dribblerOption1(payload, dribblerOption1):
        payload[20] = (dribblerOption1 & 0b00000001) | (payload[20] & 0b11111110);

    @staticmethod
    def set_dribblerOption2(payload, dribblerOption2):
        payload[21] = ((dribblerOption2 << 7) & 0b10000000) | (payload[21] & 0b01111111);

    @staticmethod
    def set_dribblerOption3(payload, dribblerOption3):
        payload[21] = ((dribblerOption3 << 6) & 0b01000000) | (payload[21] & 0b10111111);

    @staticmethod
    def set_dribblerOption4(payload, dribblerOption4):
        payload[21] = ((dribblerOption4 << 5) & 0b00100000) | (payload[21] & 0b11011111);

    @staticmethod
    def set_dribblerOption5(payload, dribblerOption5):
        payload[21] = ((dribblerOption5 << 4) & 0b00010000) | (payload[21] & 0b11101111);

    @staticmethod
    def set_dribblerOption6(payload, dribblerOption6):
        payload[21] = ((dribblerOption6 << 3) & 0b00001000) | (payload[21] & 0b11110111);

    @staticmethod
    def set_sendStateInfo(payload, sendStateInfo):
        payload[21] = ((sendStateInfo << 2) & 0b00000100) | (payload[21] & 0b11111011);

    @staticmethod
    def set_wheelsOff(payload, wheelsOff):
        payload[21] = ((wheelsOff << 1) & 0b00000010) | (payload[21] & 0b11111101);

    @staticmethod
    def set_reboot(payload, reboot):
        payload[21] = (reboot & 0b00000001) | (payload[21] & 0b11111110);

# ================================ ENCODE ================================
    def encode(self):
        payload = np.zeros(REM_BaseTypes.REM_PACKET_SIZE_REM_ROBOT_COMMAND, dtype=np.uint8)
        REM_RobotCommand.set_packetType          (payload, self.packetType)
        REM_RobotCommand.set_toRobotId           (payload, self.toRobotId)
        REM_RobotCommand.set_toColor             (payload, self.toColor)
        REM_RobotCommand.set_toBC                (payload, self.toBC)
        REM_RobotCommand.set_toBS                (payload, self.toBS)
        REM_RobotCommand.set_toPC                (payload, self.toPC)
        REM_RobotCommand.set_fromRobotId         (payload, self.fromRobotId)
        REM_RobotCommand.set_fromColor           (payload, self.fromColor)
        REM_RobotCommand.set_reserved            (payload, self.reserved)
        REM_RobotCommand.set_fromBS              (payload, self.fromBS)
        REM_RobotCommand.set_fromPC              (payload, self.fromPC)
        REM_RobotCommand.set_remVersion          (payload, self.remVersion)
        REM_RobotCommand.set_messageId           (payload, self.messageId)
        REM_RobotCommand.set_timestamp           (payload, self.timestamp)
        REM_RobotCommand.set_payloadSize         (payload, self.payloadSize)
        REM_RobotCommand.set_targetX             (payload, self.targetX)
        REM_RobotCommand.set_targetY             (payload, self.targetY)
        REM_RobotCommand.set_yaw                 (payload, self.yaw)
        REM_RobotCommand.set_cameraYaw           (payload, self.cameraYaw)
        REM_RobotCommand.set_kickChipPower       (payload, self.kickChipPower)
        REM_RobotCommand.set_doKick              (payload, self.doKick)
        REM_RobotCommand.set_doChip              (payload, self.doChip)
        REM_RobotCommand.set_kickAtYaw           (payload, self.kickAtYaw)
        REM_RobotCommand.set_doForce             (payload, self.doForce)
        REM_RobotCommand.set_useCameraYaw        (payload, self.useCameraYaw)
        REM_RobotCommand.set_useYaw              (payload, self.useYaw)
        REM_RobotCommand.set_dribblerOn          (payload, self.dribblerOn)
        REM_RobotCommand.set_dribblerOption1     (payload, self.dribblerOption1)
        REM_RobotCommand.set_dribblerOption2     (payload, self.dribblerOption2)
        REM_RobotCommand.set_dribblerOption3     (payload, self.dribblerOption3)
        REM_RobotCommand.set_dribblerOption4     (payload, self.dribblerOption4)
        REM_RobotCommand.set_dribblerOption5     (payload, self.dribblerOption5)
        REM_RobotCommand.set_dribblerOption6     (payload, self.dribblerOption6)
        REM_RobotCommand.set_sendStateInfo       (payload, self.sendStateInfo)
        REM_RobotCommand.set_wheelsOff           (payload, self.wheelsOff)
        REM_RobotCommand.set_reboot              (payload, self.reboot)
        return payload


# ================================ DECODE ================================
    def decode(self, payload):
        self.packetType       = REM_RobotCommand.get_packetType(payload)
        self.toRobotId        = REM_RobotCommand.get_toRobotId(payload)
        self.toColor          = REM_RobotCommand.get_toColor(payload)
        self.toBC             = REM_RobotCommand.get_toBC(payload)
        self.toBS             = REM_RobotCommand.get_toBS(payload)
        self.toPC             = REM_RobotCommand.get_toPC(payload)
        self.fromRobotId      = REM_RobotCommand.get_fromRobotId(payload)
        self.fromColor        = REM_RobotCommand.get_fromColor(payload)
        self.reserved         = REM_RobotCommand.get_reserved(payload)
        self.fromBS           = REM_RobotCommand.get_fromBS(payload)
        self.fromPC           = REM_RobotCommand.get_fromPC(payload)
        self.remVersion       = REM_RobotCommand.get_remVersion(payload)
        self.messageId        = REM_RobotCommand.get_messageId(payload)
        self.timestamp        = REM_RobotCommand.get_timestamp(payload)
        self.payloadSize      = REM_RobotCommand.get_payloadSize(payload)
        self.targetX          = REM_RobotCommand.get_targetX(payload)
        self.targetY          = REM_RobotCommand.get_targetY(payload)
        self.yaw              = REM_RobotCommand.get_yaw(payload)
        self.cameraYaw        = REM_RobotCommand.get_cameraYaw(payload)
        self.kickChipPower    = REM_RobotCommand.get_kickChipPower(payload)
        self.doKick           = REM_RobotCommand.get_doKick(payload)
        self.doChip           = REM_RobotCommand.get_doChip(payload)
        self.kickAtYaw        = REM_RobotCommand.get_kickAtYaw(payload)
        self.doForce          = REM_RobotCommand.get_doForce(payload)
        self.useCameraYaw     = REM_RobotCommand.get_useCameraYaw(payload)
        self.useYaw           = REM_RobotCommand.get_useYaw(payload)
        self.dribblerOn       = REM_RobotCommand.get_dribblerOn(payload)
        self.dribblerOption1  = REM_RobotCommand.get_dribblerOption1(payload)
        self.dribblerOption2  = REM_RobotCommand.get_dribblerOption2(payload)
        self.dribblerOption3  = REM_RobotCommand.get_dribblerOption3(payload)
        self.dribblerOption4  = REM_RobotCommand.get_dribblerOption4(payload)
        self.dribblerOption5  = REM_RobotCommand.get_dribblerOption5(payload)
        self.dribblerOption6  = REM_RobotCommand.get_dribblerOption6(payload)
        self.sendStateInfo    = REM_RobotCommand.get_sendStateInfo(payload)
        self.wheelsOff        = REM_RobotCommand.get_wheelsOff(payload)
        self.reboot           = REM_RobotCommand.get_reboot(payload)


    def print_bit_string(self):
        payload = self.encode()
        for i in range(len(payload)):
            print(format(payload[i], '08b'), end=" ")
        print()
