// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ] [  22  ] [  23  ] [  24  ] [  25  ] [  26  ] [  27  ] [  28  ] [  29  ] [  30  ] [  31  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- header
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- remVersion
-------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- id
-------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyX
-------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyX
-------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyX
-------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- IbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- DbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- Pwheels
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- Iwheels
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 Dwheels
*/

#ifndef __REM_P_I_D_CONFIGURATION_H
#define __REM_P_I_D_CONFIGURATION_H

#include <stdbool.h>
#include <stdint.h>
#include "REM_BaseTypes.h"

typedef struct _REM_PIDConfigurationPayload {
    uint8_t payload[PACKET_SIZE_REM_P_I_D_CONFIGURATION];
} REM_PIDConfigurationPayload;

typedef struct _REM_PIDConfiguration {
    uint32_t   header              ; // integer [0, 255]             Header byte indicating the type of packet
    uint32_t   remVersion          ; // integer [0, 15]              Version of roboteam_embedded_messages
    uint32_t   id                  ; // integer [0, 15]              Id of the robot
    float      PbodyX              ; // float   [0.000, 40.000]      Commanded P gain of the PID for body_x (x-direction)
    float      IbodyX              ; // float   [0.000, 20.000]      Commanded I gain of the PID for body_x (x-direction)
    float      DbodyX              ; // float   [0.000, 10.000]      Commanded D gain of the PID for body_x (x-direction)
    float      PbodyY              ; // float   [0.000, 40.000]      Commanded P gain of the PID for body_y (y-direction)
    float      IbodyY              ; // float   [0.000, 20.000]      Commanded I gain of the PID for body_y (y-direction)
    float      DbodyY              ; // float   [0.000, 10.000]      Commanded D gain of the PID for body_y (y-direction)
    float      PbodyW              ; // float   [0.000, 40.000]      Commanded P gain of the PID for body_w (Angular velocity)
    float      IbodyW              ; // float   [0.000, 20.000]      Commanded I gain of the PID for body_w (Angular velocity)
    float      DbodyW              ; // float   [0.000, 10.000]      Commanded D gain of the PID for body_w (Angular velocity)
    float      PbodyYaw            ; // float   [0.000, 40.000]      Commanded P gain of the PID for body_yaw (Absolute angle)
    float      IbodyYaw            ; // float   [0.000, 20.000]      Commanded I gain of the PID for body_yaw (Absolute angle)
    float      DbodyYaw            ; // float   [0.000, 10.000]      Commanded D gain of the PID for body_yaw (Absolute angle)
    float      Pwheels             ; // float   [0.000, 40.000]      Commanded P gain of the PID for the wheels
    float      Iwheels             ; // float   [0.000, 20.000]      Commanded I gain of the PID for the wheels
    float      Dwheels             ; // float   [0.000, 10.000]      Commanded D gain of the PID for the wheels
} REM_PIDConfiguration;

// ================================ GETTERS ================================
static inline uint32_t REM_PIDConfiguration_get_header(REM_PIDConfigurationPayload *rempidcp){
    return ((rempidcp->payload[0]));
}

static inline uint32_t REM_PIDConfiguration_get_remVersion(REM_PIDConfigurationPayload *rempidcp){
    return ((rempidcp->payload[1] & 0b11110000) >> 4);
}

static inline uint32_t REM_PIDConfiguration_get_id(REM_PIDConfigurationPayload *rempidcp){
    return ((rempidcp->payload[1] & 0b00001111));
}

static inline float REM_PIDConfiguration_get_PbodyX(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _PbodyX = ((rempidcp->payload[2]) << 8) | ((rempidcp->payload[3]));
    return (_PbodyX * 0.0006103608758679) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_IbodyX(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _IbodyX = ((rempidcp->payload[4]) << 8) | ((rempidcp->payload[5]));
    return (_IbodyX * 0.0003051804379339) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_DbodyX(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _DbodyX = ((rempidcp->payload[6]) << 8) | ((rempidcp->payload[7]));
    return (_DbodyX * 0.0001525902189670) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_PbodyY(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _PbodyY = ((rempidcp->payload[8]) << 8) | ((rempidcp->payload[9]));
    return (_PbodyY * 0.0006103608758679) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_IbodyY(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _IbodyY = ((rempidcp->payload[10]) << 8) | ((rempidcp->payload[11]));
    return (_IbodyY * 0.0003051804379339) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_DbodyY(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _DbodyY = ((rempidcp->payload[12]) << 8) | ((rempidcp->payload[13]));
    return (_DbodyY * 0.0001525902189670) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_PbodyW(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _PbodyW = ((rempidcp->payload[14]) << 8) | ((rempidcp->payload[15]));
    return (_PbodyW * 0.0006103608758679) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_IbodyW(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _IbodyW = ((rempidcp->payload[16]) << 8) | ((rempidcp->payload[17]));
    return (_IbodyW * 0.0003051804379339) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_DbodyW(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _DbodyW = ((rempidcp->payload[18]) << 8) | ((rempidcp->payload[19]));
    return (_DbodyW * 0.0001525902189670) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_PbodyYaw(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _PbodyYaw = ((rempidcp->payload[20]) << 8) | ((rempidcp->payload[21]));
    return (_PbodyYaw * 0.0006103608758679) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_IbodyYaw(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _IbodyYaw = ((rempidcp->payload[22]) << 8) | ((rempidcp->payload[23]));
    return (_IbodyYaw * 0.0003051804379339) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_DbodyYaw(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _DbodyYaw = ((rempidcp->payload[24]) << 8) | ((rempidcp->payload[25]));
    return (_DbodyYaw * 0.0001525902189670) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_Pwheels(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _Pwheels = ((rempidcp->payload[26]) << 8) | ((rempidcp->payload[27]));
    return (_Pwheels * 0.0006103608758679) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_Iwheels(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _Iwheels = ((rempidcp->payload[28]) << 8) | ((rempidcp->payload[29]));
    return (_Iwheels * 0.0003051804379339) + 0.0000000000000000;
}

static inline float REM_PIDConfiguration_get_Dwheels(REM_PIDConfigurationPayload *rempidcp){
    uint32_t _Dwheels = ((rempidcp->payload[30]) << 8) | ((rempidcp->payload[31]));
    return (_Dwheels * 0.0001525902189670) + 0.0000000000000000;
}

// ================================ SETTERS ================================
static inline void REM_PIDConfiguration_set_header(REM_PIDConfigurationPayload *rempidcp, uint32_t header){
    rempidcp->payload[0] = header;
}

static inline void REM_PIDConfiguration_set_remVersion(REM_PIDConfigurationPayload *rempidcp, uint32_t remVersion){
    rempidcp->payload[1] = ((remVersion << 4) & 0b11110000) | (rempidcp->payload[1] & 0b00001111);
}

static inline void REM_PIDConfiguration_set_id(REM_PIDConfigurationPayload *rempidcp, uint32_t id){
    rempidcp->payload[1] = (id & 0b00001111) | (rempidcp->payload[1] & 0b11110000);
}

static inline void REM_PIDConfiguration_set_PbodyX(REM_PIDConfigurationPayload *rempidcp, float PbodyX){
    uint32_t _PbodyX = (uint32_t)(PbodyX / 0.0006103608758679);
    rempidcp->payload[2] = (_PbodyX >> 8);
    rempidcp->payload[3] = _PbodyX;
}

static inline void REM_PIDConfiguration_set_IbodyX(REM_PIDConfigurationPayload *rempidcp, float IbodyX){
    uint32_t _IbodyX = (uint32_t)(IbodyX / 0.0003051804379339);
    rempidcp->payload[4] = (_IbodyX >> 8);
    rempidcp->payload[5] = _IbodyX;
}

static inline void REM_PIDConfiguration_set_DbodyX(REM_PIDConfigurationPayload *rempidcp, float DbodyX){
    uint32_t _DbodyX = (uint32_t)(DbodyX / 0.0001525902189670);
    rempidcp->payload[6] = (_DbodyX >> 8);
    rempidcp->payload[7] = _DbodyX;
}

static inline void REM_PIDConfiguration_set_PbodyY(REM_PIDConfigurationPayload *rempidcp, float PbodyY){
    uint32_t _PbodyY = (uint32_t)(PbodyY / 0.0006103608758679);
    rempidcp->payload[8] = (_PbodyY >> 8);
    rempidcp->payload[9] = _PbodyY;
}

static inline void REM_PIDConfiguration_set_IbodyY(REM_PIDConfigurationPayload *rempidcp, float IbodyY){
    uint32_t _IbodyY = (uint32_t)(IbodyY / 0.0003051804379339);
    rempidcp->payload[10] = (_IbodyY >> 8);
    rempidcp->payload[11] = _IbodyY;
}

static inline void REM_PIDConfiguration_set_DbodyY(REM_PIDConfigurationPayload *rempidcp, float DbodyY){
    uint32_t _DbodyY = (uint32_t)(DbodyY / 0.0001525902189670);
    rempidcp->payload[12] = (_DbodyY >> 8);
    rempidcp->payload[13] = _DbodyY;
}

static inline void REM_PIDConfiguration_set_PbodyW(REM_PIDConfigurationPayload *rempidcp, float PbodyW){
    uint32_t _PbodyW = (uint32_t)(PbodyW / 0.0006103608758679);
    rempidcp->payload[14] = (_PbodyW >> 8);
    rempidcp->payload[15] = _PbodyW;
}

static inline void REM_PIDConfiguration_set_IbodyW(REM_PIDConfigurationPayload *rempidcp, float IbodyW){
    uint32_t _IbodyW = (uint32_t)(IbodyW / 0.0003051804379339);
    rempidcp->payload[16] = (_IbodyW >> 8);
    rempidcp->payload[17] = _IbodyW;
}

static inline void REM_PIDConfiguration_set_DbodyW(REM_PIDConfigurationPayload *rempidcp, float DbodyW){
    uint32_t _DbodyW = (uint32_t)(DbodyW / 0.0001525902189670);
    rempidcp->payload[18] = (_DbodyW >> 8);
    rempidcp->payload[19] = _DbodyW;
}

static inline void REM_PIDConfiguration_set_PbodyYaw(REM_PIDConfigurationPayload *rempidcp, float PbodyYaw){
    uint32_t _PbodyYaw = (uint32_t)(PbodyYaw / 0.0006103608758679);
    rempidcp->payload[20] = (_PbodyYaw >> 8);
    rempidcp->payload[21] = _PbodyYaw;
}

static inline void REM_PIDConfiguration_set_IbodyYaw(REM_PIDConfigurationPayload *rempidcp, float IbodyYaw){
    uint32_t _IbodyYaw = (uint32_t)(IbodyYaw / 0.0003051804379339);
    rempidcp->payload[22] = (_IbodyYaw >> 8);
    rempidcp->payload[23] = _IbodyYaw;
}

static inline void REM_PIDConfiguration_set_DbodyYaw(REM_PIDConfigurationPayload *rempidcp, float DbodyYaw){
    uint32_t _DbodyYaw = (uint32_t)(DbodyYaw / 0.0001525902189670);
    rempidcp->payload[24] = (_DbodyYaw >> 8);
    rempidcp->payload[25] = _DbodyYaw;
}

static inline void REM_PIDConfiguration_set_Pwheels(REM_PIDConfigurationPayload *rempidcp, float Pwheels){
    uint32_t _Pwheels = (uint32_t)(Pwheels / 0.0006103608758679);
    rempidcp->payload[26] = (_Pwheels >> 8);
    rempidcp->payload[27] = _Pwheels;
}

static inline void REM_PIDConfiguration_set_Iwheels(REM_PIDConfigurationPayload *rempidcp, float Iwheels){
    uint32_t _Iwheels = (uint32_t)(Iwheels / 0.0003051804379339);
    rempidcp->payload[28] = (_Iwheels >> 8);
    rempidcp->payload[29] = _Iwheels;
}

static inline void REM_PIDConfiguration_set_Dwheels(REM_PIDConfigurationPayload *rempidcp, float Dwheels){
    uint32_t _Dwheels = (uint32_t)(Dwheels / 0.0001525902189670);
    rempidcp->payload[30] = (_Dwheels >> 8);
    rempidcp->payload[31] = _Dwheels;
}

// ================================ ENCODE ================================
static inline void encodeREM_PIDConfiguration(REM_PIDConfigurationPayload *rempidcp, REM_PIDConfiguration *rempidc){
    REM_PIDConfiguration_set_header              (rempidcp, rempidc->header);
    REM_PIDConfiguration_set_remVersion          (rempidcp, rempidc->remVersion);
    REM_PIDConfiguration_set_id                  (rempidcp, rempidc->id);
    REM_PIDConfiguration_set_PbodyX              (rempidcp, rempidc->PbodyX);
    REM_PIDConfiguration_set_IbodyX              (rempidcp, rempidc->IbodyX);
    REM_PIDConfiguration_set_DbodyX              (rempidcp, rempidc->DbodyX);
    REM_PIDConfiguration_set_PbodyY              (rempidcp, rempidc->PbodyY);
    REM_PIDConfiguration_set_IbodyY              (rempidcp, rempidc->IbodyY);
    REM_PIDConfiguration_set_DbodyY              (rempidcp, rempidc->DbodyY);
    REM_PIDConfiguration_set_PbodyW              (rempidcp, rempidc->PbodyW);
    REM_PIDConfiguration_set_IbodyW              (rempidcp, rempidc->IbodyW);
    REM_PIDConfiguration_set_DbodyW              (rempidcp, rempidc->DbodyW);
    REM_PIDConfiguration_set_PbodyYaw            (rempidcp, rempidc->PbodyYaw);
    REM_PIDConfiguration_set_IbodyYaw            (rempidcp, rempidc->IbodyYaw);
    REM_PIDConfiguration_set_DbodyYaw            (rempidcp, rempidc->DbodyYaw);
    REM_PIDConfiguration_set_Pwheels             (rempidcp, rempidc->Pwheels);
    REM_PIDConfiguration_set_Iwheels             (rempidcp, rempidc->Iwheels);
    REM_PIDConfiguration_set_Dwheels             (rempidcp, rempidc->Dwheels);
}

// ================================ DECODE ================================
static inline void decodeREM_PIDConfiguration(REM_PIDConfiguration *rempidc, REM_PIDConfigurationPayload *rempidcp){
    rempidc->header      = REM_PIDConfiguration_get_header(rempidcp);
    rempidc->remVersion  = REM_PIDConfiguration_get_remVersion(rempidcp);
    rempidc->id          = REM_PIDConfiguration_get_id(rempidcp);
    rempidc->PbodyX      = REM_PIDConfiguration_get_PbodyX(rempidcp);
    rempidc->IbodyX      = REM_PIDConfiguration_get_IbodyX(rempidcp);
    rempidc->DbodyX      = REM_PIDConfiguration_get_DbodyX(rempidcp);
    rempidc->PbodyY      = REM_PIDConfiguration_get_PbodyY(rempidcp);
    rempidc->IbodyY      = REM_PIDConfiguration_get_IbodyY(rempidcp);
    rempidc->DbodyY      = REM_PIDConfiguration_get_DbodyY(rempidcp);
    rempidc->PbodyW      = REM_PIDConfiguration_get_PbodyW(rempidcp);
    rempidc->IbodyW      = REM_PIDConfiguration_get_IbodyW(rempidcp);
    rempidc->DbodyW      = REM_PIDConfiguration_get_DbodyW(rempidcp);
    rempidc->PbodyYaw    = REM_PIDConfiguration_get_PbodyYaw(rempidcp);
    rempidc->IbodyYaw    = REM_PIDConfiguration_get_IbodyYaw(rempidcp);
    rempidc->DbodyYaw    = REM_PIDConfiguration_get_DbodyYaw(rempidcp);
    rempidc->Pwheels     = REM_PIDConfiguration_get_Pwheels(rempidcp);
    rempidc->Iwheels     = REM_PIDConfiguration_get_Iwheels(rempidcp);
    rempidc->Dwheels     = REM_PIDConfiguration_get_Dwheels(rempidcp);
}

#endif /*__REM_P_I_D_CONFIGURATION_H*/
