// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ] [  22  ] [  23  ] [  24  ] [  25  ] [  26  ] [  27  ] [  28  ] [  29  ] [  30  ] [  31  ] [  32  ] [  33  ] [  34  ] [  35  ] [  36  ] [  37  ] [  38  ] [  39  ] [  40  ] [  41  ] [  42  ] [  43  ] [  44  ] [  45  ] [  46  ] [  47  ] [  48  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- packetType
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toRobotId
-------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toColor
-------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBC
-------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBS
-------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toPC
-------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromRobotId
-------- -------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromColor
-------- -------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- reserved
-------- -------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromBS
-------- -------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromPC
-------- -------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- remVersion
-------- -------- -------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- messageId
-------- -------- -------- -------- 11111111 11111111 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- timestamp
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- payloadSize
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyX
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyX
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyX
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyX2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyY
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyY2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyW
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- DbodyW2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- PbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- IbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- DbodyYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- DbodyYaw2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- Pwheels
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- Iwheels
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 Dwheels
*/

#ifndef __REM_ROBOT_PIDGAINS_H
#define __REM_ROBOT_PIDGAINS_H

#include <stdbool.h>
#include <stdint.h>
#include "REM_BaseTypes.h"

typedef struct _REM_RobotPIDGainsPayload {
    uint8_t payload[REM_PACKET_SIZE_REM_ROBOT_PIDGAINS];
} REM_RobotPIDGainsPayload;

typedef struct _REM_RobotPIDGains {
    uint32_t   packetType          ; // integer [0, 255]             Byte indicating the type of packet
    uint32_t   toRobotId           ; // integer [0, 15]              Id of the receiving robot
    bool       toColor             ; // integer [0, 1]               Color of the receiving robot / basestation. Yellow = 0, Blue = 1
    bool       toBC                ; // integer [0, 1]               Bit indicating this packet has to be broadcasted to all robots
    bool       toBS                ; // integer [0, 1]               Bit indicating this packet is meant for the basestation
    bool       toPC                ; // integer [0, 1]               Bit indicating this packet is meant for the PC
    uint32_t   fromRobotId         ; // integer [0, 15]              Id of the transmitting robot
    bool       fromColor           ; // integer [0, 1]               Color of the transmitting robot / basestation. Yellow = 0, Blue = 1
    bool       reserved            ; // integer [0, 1]               reserved
    bool       fromBS              ; // integer [0, 1]               Bit indicating this packet is coming from the basestation
    bool       fromPC              ; // integer [0, 1]               Bit indicating this packet is coming from the PC
    uint32_t   remVersion          ; // integer [0, 15]              Version of roboteam_embedded_messages
    uint32_t   messageId           ; // integer [0, 15]              messageId. Can be used for aligning packets
    uint64_t   timestamp           ; // integer [0, 281474976710655] Unix Timestamp in milliseconds
    uint32_t   payloadSize         ; // integer [0, 255]             Size of the payload. At most 255 bytes including the generic_packet_header. Keep the 127 byte SX1280 limit in mind
    float      PbodyX              ; // float   [0.000, 100.000]     Received P gain of the PID for body_x (x-direction)
    float      IbodyX              ; // float   [0.000, 100.000]     Received I gain of the PID for body_x (x-direction)
    float      DbodyX              ; // float   [0.000, 100.000]     Received D gain of the PID for body_x (x-direction)
    float      DbodyX2             ; // float   [0.000, 100.000]     Received second D gain of the PID for body_x (x-direction)
    float      PbodyY              ; // float   [0.000, 100.000]     Received P gain of the PID for body_y (y-direction)
    float      IbodyY              ; // float   [0.000, 100.000]     Received I gain of the PID for body_y (y-direction)
    float      DbodyY              ; // float   [0.000, 100.000]     Received D gain of the PID for body_y (y-direction)
    float      DbodyY2             ; // float   [0.000, 100.000]     Received second D gain of the PID for body_y (y-direction)
    float      PbodyW              ; // float   [0.000, 100.000]     Received P gain of the PID for body_w (Angular velocity)
    float      IbodyW              ; // float   [0.000, 100.000]     Received I gain of the PID for body_w (Angular velocity)
    float      DbodyW              ; // float   [0.000, 100.000]     Received D gain of the PID for body_w (Angular velocity)
    float      DbodyW2             ; // float   [0.000, 100.000]     Received second D gain of the PID for body_w (w-direction)
    float      PbodyYaw            ; // float   [0.000, 100.000]     Received P gain of the PID for body_yaw (Absolute angle)
    float      IbodyYaw            ; // float   [0.000, 100.000]     Received I gain of the PID for body_yaw (Absolute angle)
    float      DbodyYaw            ; // float   [0.000, 100.000]     Received D gain of the PID for body_yaw (Absolute angle)
    float      DbodyYaw2           ; // float   [0.000, 100.000]     Received second D gain of the PID for body_taw (Absolute angle)
    float      Pwheels             ; // float   [0.000, 100.000]     Received P gain of the PID for the wheels
    float      Iwheels             ; // float   [0.000, 100.000]     Received I gain of the PID for the wheels
    float      Dwheels             ; // float   [0.000, 100.000]     Received D gain of the PID for the wheels
} REM_RobotPIDGains;

// ================================ GETTERS ================================
static inline uint32_t REM_RobotPIDGains_get_packetType(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[0]));
}

static inline uint32_t REM_RobotPIDGains_get_toRobotId(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[1] & 0b11110000) >> 4);
}

static inline bool REM_RobotPIDGains_get_toColor(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[1] & 0b00001000) > 0;
}

static inline bool REM_RobotPIDGains_get_toBC(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[1] & 0b00000100) > 0;
}

static inline bool REM_RobotPIDGains_get_toBS(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[1] & 0b00000010) > 0;
}

static inline bool REM_RobotPIDGains_get_toPC(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[1] & 0b00000001) > 0;
}

static inline uint32_t REM_RobotPIDGains_get_fromRobotId(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[2] & 0b11110000) >> 4);
}

static inline bool REM_RobotPIDGains_get_fromColor(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[2] & 0b00001000) > 0;
}

static inline bool REM_RobotPIDGains_get_reserved(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[2] & 0b00000100) > 0;
}

static inline bool REM_RobotPIDGains_get_fromBS(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[2] & 0b00000010) > 0;
}

static inline bool REM_RobotPIDGains_get_fromPC(REM_RobotPIDGainsPayload *remrpidgp){
    return (remrpidgp->payload[2] & 0b00000001) > 0;
}

static inline uint32_t REM_RobotPIDGains_get_remVersion(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[3] & 0b11110000) >> 4);
}

static inline uint32_t REM_RobotPIDGains_get_messageId(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[3] & 0b00001111));
}

static inline uint64_t REM_RobotPIDGains_get_timestamp(REM_RobotPIDGainsPayload *remrpidgp){
    return ((uint64_t) (remrpidgp->payload[4]) << 40) | ((uint64_t) (remrpidgp->payload[5]) << 32) | ((uint32_t) (remrpidgp->payload[6]) << 24) | ((remrpidgp->payload[7]) << 16) | ((remrpidgp->payload[8]) << 8) | ((remrpidgp->payload[9]));
}

static inline uint32_t REM_RobotPIDGains_get_payloadSize(REM_RobotPIDGainsPayload *remrpidgp){
    return ((remrpidgp->payload[10]));
}

static inline float REM_RobotPIDGains_get_PbodyX(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _PbodyX = ((remrpidgp->payload[11]) << 8) | ((remrpidgp->payload[12]));
    return (_PbodyX * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_IbodyX(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _IbodyX = ((remrpidgp->payload[13]) << 8) | ((remrpidgp->payload[14]));
    return (_IbodyX * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyX(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyX = ((remrpidgp->payload[15]) << 8) | ((remrpidgp->payload[16]));
    return (_DbodyX * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyX2(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyX2 = ((remrpidgp->payload[17]) << 8) | ((remrpidgp->payload[18]));
    return (_DbodyX2 * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_PbodyY(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _PbodyY = ((remrpidgp->payload[19]) << 8) | ((remrpidgp->payload[20]));
    return (_PbodyY * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_IbodyY(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _IbodyY = ((remrpidgp->payload[21]) << 8) | ((remrpidgp->payload[22]));
    return (_IbodyY * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyY(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyY = ((remrpidgp->payload[23]) << 8) | ((remrpidgp->payload[24]));
    return (_DbodyY * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyY2(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyY2 = ((remrpidgp->payload[25]) << 8) | ((remrpidgp->payload[26]));
    return (_DbodyY2 * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_PbodyW(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _PbodyW = ((remrpidgp->payload[27]) << 8) | ((remrpidgp->payload[28]));
    return (_PbodyW * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_IbodyW(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _IbodyW = ((remrpidgp->payload[29]) << 8) | ((remrpidgp->payload[30]));
    return (_IbodyW * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyW(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyW = ((remrpidgp->payload[31]) << 8) | ((remrpidgp->payload[32]));
    return (_DbodyW * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyW2(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyW2 = ((remrpidgp->payload[33]) << 8) | ((remrpidgp->payload[34]));
    return (_DbodyW2 * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_PbodyYaw(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _PbodyYaw = ((remrpidgp->payload[35]) << 8) | ((remrpidgp->payload[36]));
    return (_PbodyYaw * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_IbodyYaw(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _IbodyYaw = ((remrpidgp->payload[37]) << 8) | ((remrpidgp->payload[38]));
    return (_IbodyYaw * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyYaw(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyYaw = ((remrpidgp->payload[39]) << 8) | ((remrpidgp->payload[40]));
    return (_DbodyYaw * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_DbodyYaw2(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _DbodyYaw2 = ((remrpidgp->payload[41]) << 8) | ((remrpidgp->payload[42]));
    return (_DbodyYaw2 * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_Pwheels(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _Pwheels = ((remrpidgp->payload[43]) << 8) | ((remrpidgp->payload[44]));
    return (_Pwheels * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_Iwheels(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _Iwheels = ((remrpidgp->payload[45]) << 8) | ((remrpidgp->payload[46]));
    return (_Iwheels * 0.0015259021896696F);
}

static inline float REM_RobotPIDGains_get_Dwheels(REM_RobotPIDGainsPayload *remrpidgp){
    uint32_t _Dwheels = ((remrpidgp->payload[47]) << 8) | ((remrpidgp->payload[48]));
    return (_Dwheels * 0.0015259021896696F);
}

// ================================ SETTERS ================================
static inline void REM_RobotPIDGains_set_packetType(REM_RobotPIDGainsPayload *remrpidgp, uint32_t packetType){
    remrpidgp->payload[0] = packetType;
}

static inline void REM_RobotPIDGains_set_toRobotId(REM_RobotPIDGainsPayload *remrpidgp, uint32_t toRobotId){
    remrpidgp->payload[1] = ((toRobotId << 4) & 0b11110000) | (remrpidgp->payload[1] & 0b00001111);
}

static inline void REM_RobotPIDGains_set_toColor(REM_RobotPIDGainsPayload *remrpidgp, bool toColor){
    remrpidgp->payload[1] = ((toColor << 3) & 0b00001000) | (remrpidgp->payload[1] & 0b11110111);
}

static inline void REM_RobotPIDGains_set_toBC(REM_RobotPIDGainsPayload *remrpidgp, bool toBC){
    remrpidgp->payload[1] = ((toBC << 2) & 0b00000100) | (remrpidgp->payload[1] & 0b11111011);
}

static inline void REM_RobotPIDGains_set_toBS(REM_RobotPIDGainsPayload *remrpidgp, bool toBS){
    remrpidgp->payload[1] = ((toBS << 1) & 0b00000010) | (remrpidgp->payload[1] & 0b11111101);
}

static inline void REM_RobotPIDGains_set_toPC(REM_RobotPIDGainsPayload *remrpidgp, bool toPC){
    remrpidgp->payload[1] = (toPC & 0b00000001) | (remrpidgp->payload[1] & 0b11111110);
}

static inline void REM_RobotPIDGains_set_fromRobotId(REM_RobotPIDGainsPayload *remrpidgp, uint32_t fromRobotId){
    remrpidgp->payload[2] = ((fromRobotId << 4) & 0b11110000) | (remrpidgp->payload[2] & 0b00001111);
}

static inline void REM_RobotPIDGains_set_fromColor(REM_RobotPIDGainsPayload *remrpidgp, bool fromColor){
    remrpidgp->payload[2] = ((fromColor << 3) & 0b00001000) | (remrpidgp->payload[2] & 0b11110111);
}

static inline void REM_RobotPIDGains_set_reserved(REM_RobotPIDGainsPayload *remrpidgp, bool reserved){
    remrpidgp->payload[2] = ((reserved << 2) & 0b00000100) | (remrpidgp->payload[2] & 0b11111011);
}

static inline void REM_RobotPIDGains_set_fromBS(REM_RobotPIDGainsPayload *remrpidgp, bool fromBS){
    remrpidgp->payload[2] = ((fromBS << 1) & 0b00000010) | (remrpidgp->payload[2] & 0b11111101);
}

static inline void REM_RobotPIDGains_set_fromPC(REM_RobotPIDGainsPayload *remrpidgp, bool fromPC){
    remrpidgp->payload[2] = (fromPC & 0b00000001) | (remrpidgp->payload[2] & 0b11111110);
}

static inline void REM_RobotPIDGains_set_remVersion(REM_RobotPIDGainsPayload *remrpidgp, uint32_t remVersion){
    remrpidgp->payload[3] = ((remVersion << 4) & 0b11110000) | (remrpidgp->payload[3] & 0b00001111);
}

static inline void REM_RobotPIDGains_set_messageId(REM_RobotPIDGainsPayload *remrpidgp, uint32_t messageId){
    remrpidgp->payload[3] = (messageId & 0b00001111) | (remrpidgp->payload[3] & 0b11110000);
}

static inline void REM_RobotPIDGains_set_timestamp(REM_RobotPIDGainsPayload *remrpidgp, uint64_t timestamp){
    remrpidgp->payload[4] = (timestamp >> 40);
    remrpidgp->payload[5] = (timestamp >> 32);
    remrpidgp->payload[6] = (timestamp >> 24);
    remrpidgp->payload[7] = (timestamp >> 16);
    remrpidgp->payload[8] = (timestamp >> 8);
    remrpidgp->payload[9] = timestamp;
}

static inline void REM_RobotPIDGains_set_payloadSize(REM_RobotPIDGainsPayload *remrpidgp, uint32_t payloadSize){
    remrpidgp->payload[10] = payloadSize;
}

static inline void REM_RobotPIDGains_set_PbodyX(REM_RobotPIDGainsPayload *remrpidgp, float PbodyX){
    uint32_t _PbodyX = (uint32_t)(PbodyX / 0.0015259021896696F);
    remrpidgp->payload[11] = (_PbodyX >> 8);
    remrpidgp->payload[12] = _PbodyX;
}

static inline void REM_RobotPIDGains_set_IbodyX(REM_RobotPIDGainsPayload *remrpidgp, float IbodyX){
    uint32_t _IbodyX = (uint32_t)(IbodyX / 0.0015259021896696F);
    remrpidgp->payload[13] = (_IbodyX >> 8);
    remrpidgp->payload[14] = _IbodyX;
}

static inline void REM_RobotPIDGains_set_DbodyX(REM_RobotPIDGainsPayload *remrpidgp, float DbodyX){
    uint32_t _DbodyX = (uint32_t)(DbodyX / 0.0015259021896696F);
    remrpidgp->payload[15] = (_DbodyX >> 8);
    remrpidgp->payload[16] = _DbodyX;
}

static inline void REM_RobotPIDGains_set_DbodyX2(REM_RobotPIDGainsPayload *remrpidgp, float DbodyX2){
    uint32_t _DbodyX2 = (uint32_t)(DbodyX2 / 0.0015259021896696F);
    remrpidgp->payload[17] = (_DbodyX2 >> 8);
    remrpidgp->payload[18] = _DbodyX2;
}

static inline void REM_RobotPIDGains_set_PbodyY(REM_RobotPIDGainsPayload *remrpidgp, float PbodyY){
    uint32_t _PbodyY = (uint32_t)(PbodyY / 0.0015259021896696F);
    remrpidgp->payload[19] = (_PbodyY >> 8);
    remrpidgp->payload[20] = _PbodyY;
}

static inline void REM_RobotPIDGains_set_IbodyY(REM_RobotPIDGainsPayload *remrpidgp, float IbodyY){
    uint32_t _IbodyY = (uint32_t)(IbodyY / 0.0015259021896696F);
    remrpidgp->payload[21] = (_IbodyY >> 8);
    remrpidgp->payload[22] = _IbodyY;
}

static inline void REM_RobotPIDGains_set_DbodyY(REM_RobotPIDGainsPayload *remrpidgp, float DbodyY){
    uint32_t _DbodyY = (uint32_t)(DbodyY / 0.0015259021896696F);
    remrpidgp->payload[23] = (_DbodyY >> 8);
    remrpidgp->payload[24] = _DbodyY;
}

static inline void REM_RobotPIDGains_set_DbodyY2(REM_RobotPIDGainsPayload *remrpidgp, float DbodyY2){
    uint32_t _DbodyY2 = (uint32_t)(DbodyY2 / 0.0015259021896696F);
    remrpidgp->payload[25] = (_DbodyY2 >> 8);
    remrpidgp->payload[26] = _DbodyY2;
}

static inline void REM_RobotPIDGains_set_PbodyW(REM_RobotPIDGainsPayload *remrpidgp, float PbodyW){
    uint32_t _PbodyW = (uint32_t)(PbodyW / 0.0015259021896696F);
    remrpidgp->payload[27] = (_PbodyW >> 8);
    remrpidgp->payload[28] = _PbodyW;
}

static inline void REM_RobotPIDGains_set_IbodyW(REM_RobotPIDGainsPayload *remrpidgp, float IbodyW){
    uint32_t _IbodyW = (uint32_t)(IbodyW / 0.0015259021896696F);
    remrpidgp->payload[29] = (_IbodyW >> 8);
    remrpidgp->payload[30] = _IbodyW;
}

static inline void REM_RobotPIDGains_set_DbodyW(REM_RobotPIDGainsPayload *remrpidgp, float DbodyW){
    uint32_t _DbodyW = (uint32_t)(DbodyW / 0.0015259021896696F);
    remrpidgp->payload[31] = (_DbodyW >> 8);
    remrpidgp->payload[32] = _DbodyW;
}

static inline void REM_RobotPIDGains_set_DbodyW2(REM_RobotPIDGainsPayload *remrpidgp, float DbodyW2){
    uint32_t _DbodyW2 = (uint32_t)(DbodyW2 / 0.0015259021896696F);
    remrpidgp->payload[33] = (_DbodyW2 >> 8);
    remrpidgp->payload[34] = _DbodyW2;
}

static inline void REM_RobotPIDGains_set_PbodyYaw(REM_RobotPIDGainsPayload *remrpidgp, float PbodyYaw){
    uint32_t _PbodyYaw = (uint32_t)(PbodyYaw / 0.0015259021896696F);
    remrpidgp->payload[35] = (_PbodyYaw >> 8);
    remrpidgp->payload[36] = _PbodyYaw;
}

static inline void REM_RobotPIDGains_set_IbodyYaw(REM_RobotPIDGainsPayload *remrpidgp, float IbodyYaw){
    uint32_t _IbodyYaw = (uint32_t)(IbodyYaw / 0.0015259021896696F);
    remrpidgp->payload[37] = (_IbodyYaw >> 8);
    remrpidgp->payload[38] = _IbodyYaw;
}

static inline void REM_RobotPIDGains_set_DbodyYaw(REM_RobotPIDGainsPayload *remrpidgp, float DbodyYaw){
    uint32_t _DbodyYaw = (uint32_t)(DbodyYaw / 0.0015259021896696F);
    remrpidgp->payload[39] = (_DbodyYaw >> 8);
    remrpidgp->payload[40] = _DbodyYaw;
}

static inline void REM_RobotPIDGains_set_DbodyYaw2(REM_RobotPIDGainsPayload *remrpidgp, float DbodyYaw2){
    uint32_t _DbodyYaw2 = (uint32_t)(DbodyYaw2 / 0.0015259021896696F);
    remrpidgp->payload[41] = (_DbodyYaw2 >> 8);
    remrpidgp->payload[42] = _DbodyYaw2;
}

static inline void REM_RobotPIDGains_set_Pwheels(REM_RobotPIDGainsPayload *remrpidgp, float Pwheels){
    uint32_t _Pwheels = (uint32_t)(Pwheels / 0.0015259021896696F);
    remrpidgp->payload[43] = (_Pwheels >> 8);
    remrpidgp->payload[44] = _Pwheels;
}

static inline void REM_RobotPIDGains_set_Iwheels(REM_RobotPIDGainsPayload *remrpidgp, float Iwheels){
    uint32_t _Iwheels = (uint32_t)(Iwheels / 0.0015259021896696F);
    remrpidgp->payload[45] = (_Iwheels >> 8);
    remrpidgp->payload[46] = _Iwheels;
}

static inline void REM_RobotPIDGains_set_Dwheels(REM_RobotPIDGainsPayload *remrpidgp, float Dwheels){
    uint32_t _Dwheels = (uint32_t)(Dwheels / 0.0015259021896696F);
    remrpidgp->payload[47] = (_Dwheels >> 8);
    remrpidgp->payload[48] = _Dwheels;
}

// ================================ ENCODE ================================
static inline void encodeREM_RobotPIDGains(REM_RobotPIDGainsPayload *remrpidgp, REM_RobotPIDGains *remrpidg){
    REM_RobotPIDGains_set_packetType          (remrpidgp, remrpidg->packetType);
    REM_RobotPIDGains_set_toRobotId           (remrpidgp, remrpidg->toRobotId);
    REM_RobotPIDGains_set_toColor             (remrpidgp, remrpidg->toColor);
    REM_RobotPIDGains_set_toBC                (remrpidgp, remrpidg->toBC);
    REM_RobotPIDGains_set_toBS                (remrpidgp, remrpidg->toBS);
    REM_RobotPIDGains_set_toPC                (remrpidgp, remrpidg->toPC);
    REM_RobotPIDGains_set_fromRobotId         (remrpidgp, remrpidg->fromRobotId);
    REM_RobotPIDGains_set_fromColor           (remrpidgp, remrpidg->fromColor);
    REM_RobotPIDGains_set_reserved            (remrpidgp, remrpidg->reserved);
    REM_RobotPIDGains_set_fromBS              (remrpidgp, remrpidg->fromBS);
    REM_RobotPIDGains_set_fromPC              (remrpidgp, remrpidg->fromPC);
    REM_RobotPIDGains_set_remVersion          (remrpidgp, remrpidg->remVersion);
    REM_RobotPIDGains_set_messageId           (remrpidgp, remrpidg->messageId);
    REM_RobotPIDGains_set_timestamp           (remrpidgp, remrpidg->timestamp);
    REM_RobotPIDGains_set_payloadSize         (remrpidgp, remrpidg->payloadSize);
    REM_RobotPIDGains_set_PbodyX              (remrpidgp, remrpidg->PbodyX);
    REM_RobotPIDGains_set_IbodyX              (remrpidgp, remrpidg->IbodyX);
    REM_RobotPIDGains_set_DbodyX              (remrpidgp, remrpidg->DbodyX);
    REM_RobotPIDGains_set_DbodyX2             (remrpidgp, remrpidg->DbodyX2);
    REM_RobotPIDGains_set_PbodyY              (remrpidgp, remrpidg->PbodyY);
    REM_RobotPIDGains_set_IbodyY              (remrpidgp, remrpidg->IbodyY);
    REM_RobotPIDGains_set_DbodyY              (remrpidgp, remrpidg->DbodyY);
    REM_RobotPIDGains_set_DbodyY2             (remrpidgp, remrpidg->DbodyY2);
    REM_RobotPIDGains_set_PbodyW              (remrpidgp, remrpidg->PbodyW);
    REM_RobotPIDGains_set_IbodyW              (remrpidgp, remrpidg->IbodyW);
    REM_RobotPIDGains_set_DbodyW              (remrpidgp, remrpidg->DbodyW);
    REM_RobotPIDGains_set_DbodyW2             (remrpidgp, remrpidg->DbodyW2);
    REM_RobotPIDGains_set_PbodyYaw            (remrpidgp, remrpidg->PbodyYaw);
    REM_RobotPIDGains_set_IbodyYaw            (remrpidgp, remrpidg->IbodyYaw);
    REM_RobotPIDGains_set_DbodyYaw            (remrpidgp, remrpidg->DbodyYaw);
    REM_RobotPIDGains_set_DbodyYaw2           (remrpidgp, remrpidg->DbodyYaw2);
    REM_RobotPIDGains_set_Pwheels             (remrpidgp, remrpidg->Pwheels);
    REM_RobotPIDGains_set_Iwheels             (remrpidgp, remrpidg->Iwheels);
    REM_RobotPIDGains_set_Dwheels             (remrpidgp, remrpidg->Dwheels);
}

// ================================ DECODE ================================
static inline void decodeREM_RobotPIDGains(REM_RobotPIDGains *remrpidg, REM_RobotPIDGainsPayload *remrpidgp){
    remrpidg->packetType = REM_RobotPIDGains_get_packetType(remrpidgp);
    remrpidg->toRobotId  = REM_RobotPIDGains_get_toRobotId(remrpidgp);
    remrpidg->toColor    = REM_RobotPIDGains_get_toColor(remrpidgp);
    remrpidg->toBC       = REM_RobotPIDGains_get_toBC(remrpidgp);
    remrpidg->toBS       = REM_RobotPIDGains_get_toBS(remrpidgp);
    remrpidg->toPC       = REM_RobotPIDGains_get_toPC(remrpidgp);
    remrpidg->fromRobotId= REM_RobotPIDGains_get_fromRobotId(remrpidgp);
    remrpidg->fromColor  = REM_RobotPIDGains_get_fromColor(remrpidgp);
    remrpidg->reserved   = REM_RobotPIDGains_get_reserved(remrpidgp);
    remrpidg->fromBS     = REM_RobotPIDGains_get_fromBS(remrpidgp);
    remrpidg->fromPC     = REM_RobotPIDGains_get_fromPC(remrpidgp);
    remrpidg->remVersion = REM_RobotPIDGains_get_remVersion(remrpidgp);
    remrpidg->messageId  = REM_RobotPIDGains_get_messageId(remrpidgp);
    remrpidg->timestamp  = REM_RobotPIDGains_get_timestamp(remrpidgp);
    remrpidg->payloadSize= REM_RobotPIDGains_get_payloadSize(remrpidgp);
    remrpidg->PbodyX     = REM_RobotPIDGains_get_PbodyX(remrpidgp);
    remrpidg->IbodyX     = REM_RobotPIDGains_get_IbodyX(remrpidgp);
    remrpidg->DbodyX     = REM_RobotPIDGains_get_DbodyX(remrpidgp);
    remrpidg->DbodyX2    = REM_RobotPIDGains_get_DbodyX2(remrpidgp);
    remrpidg->PbodyY     = REM_RobotPIDGains_get_PbodyY(remrpidgp);
    remrpidg->IbodyY     = REM_RobotPIDGains_get_IbodyY(remrpidgp);
    remrpidg->DbodyY     = REM_RobotPIDGains_get_DbodyY(remrpidgp);
    remrpidg->DbodyY2    = REM_RobotPIDGains_get_DbodyY2(remrpidgp);
    remrpidg->PbodyW     = REM_RobotPIDGains_get_PbodyW(remrpidgp);
    remrpidg->IbodyW     = REM_RobotPIDGains_get_IbodyW(remrpidgp);
    remrpidg->DbodyW     = REM_RobotPIDGains_get_DbodyW(remrpidgp);
    remrpidg->DbodyW2    = REM_RobotPIDGains_get_DbodyW2(remrpidgp);
    remrpidg->PbodyYaw   = REM_RobotPIDGains_get_PbodyYaw(remrpidgp);
    remrpidg->IbodyYaw   = REM_RobotPIDGains_get_IbodyYaw(remrpidgp);
    remrpidg->DbodyYaw   = REM_RobotPIDGains_get_DbodyYaw(remrpidgp);
    remrpidg->DbodyYaw2  = REM_RobotPIDGains_get_DbodyYaw2(remrpidgp);
    remrpidg->Pwheels    = REM_RobotPIDGains_get_Pwheels(remrpidgp);
    remrpidg->Iwheels    = REM_RobotPIDGains_get_Iwheels(remrpidgp);
    remrpidg->Dwheels    = REM_RobotPIDGains_get_Dwheels(remrpidgp);
}

#endif /*__REM_ROBOT_PIDGAINS_H*/
