// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ] [  22  ] [  23  ] [  24  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- packetType
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toRobotId
-------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toColor
-------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBC
-------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toBS
-------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- toPC
-------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromRobotId
-------- -------- ----1--- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromColor
-------- -------- -----1-- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- reserved
-------- -------- ------1- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromBS
-------- -------- -------1 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- fromPC
-------- -------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- remVersion
-------- -------- -------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- messageId
-------- -------- -------- -------- 11111111 11111111 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- timestamp
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- payloadSize
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- rho
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- theta
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- yaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- -------- -------- angularVelocity
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 -------- -------- -------- -------- cameraYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- -------- dribbler
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 -------- -------- kickChipPower
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 1------- -------- doKick
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -1------ -------- doChip
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- --1----- -------- kickAtYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ---1---- -------- doForce
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1--- -------- useCameraAngle
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -----1-- -------- useYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ------1- -------- wheelsOff
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------1 -------- feedback
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 1------- reboot
*/

#ifndef __REM_ROBOT_COMMAND_H
#define __REM_ROBOT_COMMAND_H

#include <stdbool.h>
#include <stdint.h>
#include "REM_BaseTypes.h"

typedef struct _REM_RobotCommandPayload {
    uint8_t payload[REM_PACKET_SIZE_REM_ROBOT_COMMAND];
} REM_RobotCommandPayload;

typedef struct _REM_RobotCommand {
    uint32_t   packetType          ; // integer [0, 255]             Header byte indicating the type of packet
    uint32_t   toRobotId           ; // integer [0, 15]              Id of the receiving robot
    bool       toColor             ; // integer [0, 1]               Color of the receiving robot / basestation. Yellow = 0, Blue = 1
    bool       toBC                ; // integer [0, 1]               Bit indicating this packet has to be broadcasted to all robots
    bool       toBS                ; // integer [0, 1]               Bit indicating this packet is meant for the basestation
    bool       toPC                ; // integer [0, 1]               Bit indicating this packet is meant for the PC
    uint32_t   fromRobotId         ; // integer [0, 15]              Id of the transmitting robot
    bool       fromColor           ; // integer [0, 1]               Color of the transmitting robot / basestation. Yellow = 0, Blue = 1
    bool       reserved            ; // integer [0, 1]               reserved
    bool       fromBS              ; // integer [0, 1]               Bit indicating this packet is coming from the basestation
    bool       fromPC              ; // integer [0, 1]               Bit indicating this packet is coming from the PC
    uint32_t   remVersion          ; // integer [0, 15]              Version of roboteam_embedded_messages
    uint32_t   messageId           ; // integer [0, 15]              messageId. Can be used for aligning packets
    uint64_t   timestamp           ; // integer [0, 281474976710655] Unix Timestamp in centiseconds
    uint32_t   payloadSize         ; // integer [0, 255]             Size of the payload. At most 255 bytes including the generic_packet_header. Keep the 127 byte SX1280 limit in mind
    float      rho                 ; // float   [0.000, 30.000]      Magnitude of movement (m/s)
    float      theta               ; // float   [-3.142, 3.142]      Direction of movement (radians)
    float      yaw                 ; // float   [-3.142, 3.142]      Absolute facing angle (rad)
    float      angularVelocity     ; // float   [-31.416, 31.416]    Angular velocity (rad/s)
    float      cameraYaw           ; // float   [-3.142, 3.142]      Angle of the robot as seen by camera (rad)
    float      dribbler            ; // float   [0.000, 1.000]       Dribbler speed
    float      kickChipPower       ; // float   [0.000, 6.500]       Speed of the ball in m/s
    bool       doKick              ; // integer [0, 1]               Do a kick if ballsensor
    bool       doChip              ; // integer [0, 1]               Do a chip if ballsensor
    bool       kickAtYaw           ; // integer [0, 1]               Do a kick once yaw is reached
    bool       doForce             ; // integer [0, 1]               Do regardless of ballsensor
    bool       useCameraAngle      ; // integer [0, 1]               Use the info in 'cameraYaw'
    bool       useYaw              ; // integer [0, 1]               0 = angular velocity, 1 = yaw
    bool       wheelsOff           ; // integer [0, 1]               Indicate that the robot should stop moving
    bool       feedback            ; // integer [0, 1]               Ignore the packet. Just send feedback
    bool       reboot              ; // integer [0, 1]               Reboot the robot remotely
} REM_RobotCommand;

// ================================ GETTERS ================================
static inline uint32_t REM_RobotCommand_get_packetType(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[0]));
}

static inline uint32_t REM_RobotCommand_get_toRobotId(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[1] & 0b11110000) >> 4);
}

static inline bool REM_RobotCommand_get_toColor(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[1] & 0b00001000) > 0;
}

static inline bool REM_RobotCommand_get_toBC(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[1] & 0b00000100) > 0;
}

static inline bool REM_RobotCommand_get_toBS(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[1] & 0b00000010) > 0;
}

static inline bool REM_RobotCommand_get_toPC(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[1] & 0b00000001) > 0;
}

static inline uint32_t REM_RobotCommand_get_fromRobotId(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[2] & 0b11110000) >> 4);
}

static inline bool REM_RobotCommand_get_fromColor(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[2] & 0b00001000) > 0;
}

static inline bool REM_RobotCommand_get_reserved(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[2] & 0b00000100) > 0;
}

static inline bool REM_RobotCommand_get_fromBS(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[2] & 0b00000010) > 0;
}

static inline bool REM_RobotCommand_get_fromPC(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[2] & 0b00000001) > 0;
}

static inline uint32_t REM_RobotCommand_get_remVersion(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[3] & 0b11110000) >> 4);
}

static inline uint32_t REM_RobotCommand_get_messageId(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[3] & 0b00001111));
}

static inline uint64_t REM_RobotCommand_get_timestamp(REM_RobotCommandPayload *remrcp){
    return ((uint64_t) (remrcp->payload[4]) << 40) | ((uint64_t) (remrcp->payload[5]) << 32) | ((uint32_t) (remrcp->payload[6]) << 24) | ((remrcp->payload[7]) << 16) | ((remrcp->payload[8]) << 8) | ((remrcp->payload[9]));
}

static inline uint32_t REM_RobotCommand_get_payloadSize(REM_RobotCommandPayload *remrcp){
    return ((remrcp->payload[10]));
}

static inline float REM_RobotCommand_get_rho(REM_RobotCommandPayload *remrcp){
    uint32_t _rho = ((remrcp->payload[11]) << 8) | ((remrcp->payload[12]));
    return (_rho * 0.0004577706569009F);
}

static inline float REM_RobotCommand_get_theta(REM_RobotCommandPayload *remrcp){
    uint32_t _theta = ((remrcp->payload[13]) << 8) | ((remrcp->payload[14]));
    return (_theta * 0.0000958752621833F) + -3.1415926535897931F;
}

static inline float REM_RobotCommand_get_yaw(REM_RobotCommandPayload *remrcp){
    uint32_t _yaw = ((remrcp->payload[15]) << 8) | ((remrcp->payload[16]));
    return (_yaw * 0.0000958752621833F) + -3.1415926535897931F;
}

static inline float REM_RobotCommand_get_angularVelocity(REM_RobotCommandPayload *remrcp){
    uint32_t _angularVelocity = ((remrcp->payload[17]) << 8) | ((remrcp->payload[18]));
    return (_angularVelocity * 0.0009587526218325F) + -31.4159265358979312F;
}

static inline float REM_RobotCommand_get_cameraYaw(REM_RobotCommandPayload *remrcp){
    uint32_t _cameraYaw = ((remrcp->payload[19]) << 8) | ((remrcp->payload[20]));
    return (_cameraYaw * 0.0000958752621833F) + -3.1415926535897931F;
}

static inline float REM_RobotCommand_get_dribbler(REM_RobotCommandPayload *remrcp){
    uint32_t _dribbler = ((remrcp->payload[21]));
    return (_dribbler * 0.0039215686274510F);
}

static inline float REM_RobotCommand_get_kickChipPower(REM_RobotCommandPayload *remrcp){
    uint32_t _kickChipPower = ((remrcp->payload[22]));
    return (_kickChipPower * 0.0254901960784314F);
}

static inline bool REM_RobotCommand_get_doKick(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b10000000) > 0;
}

static inline bool REM_RobotCommand_get_doChip(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b01000000) > 0;
}

static inline bool REM_RobotCommand_get_kickAtYaw(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00100000) > 0;
}

static inline bool REM_RobotCommand_get_doForce(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00010000) > 0;
}

static inline bool REM_RobotCommand_get_useCameraAngle(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00001000) > 0;
}

static inline bool REM_RobotCommand_get_useYaw(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00000100) > 0;
}

static inline bool REM_RobotCommand_get_wheelsOff(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00000010) > 0;
}

static inline bool REM_RobotCommand_get_feedback(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[23] & 0b00000001) > 0;
}

static inline bool REM_RobotCommand_get_reboot(REM_RobotCommandPayload *remrcp){
    return (remrcp->payload[24] & 0b10000000) > 0;
}

// ================================ SETTERS ================================
static inline void REM_RobotCommand_set_packetType(REM_RobotCommandPayload *remrcp, uint32_t packetType){
    remrcp->payload[0] = packetType;
}

static inline void REM_RobotCommand_set_toRobotId(REM_RobotCommandPayload *remrcp, uint32_t toRobotId){
    remrcp->payload[1] = ((toRobotId << 4) & 0b11110000) | (remrcp->payload[1] & 0b00001111);
}

static inline void REM_RobotCommand_set_toColor(REM_RobotCommandPayload *remrcp, bool toColor){
    remrcp->payload[1] = ((toColor << 3) & 0b00001000) | (remrcp->payload[1] & 0b11110111);
}

static inline void REM_RobotCommand_set_toBC(REM_RobotCommandPayload *remrcp, bool toBC){
    remrcp->payload[1] = ((toBC << 2) & 0b00000100) | (remrcp->payload[1] & 0b11111011);
}

static inline void REM_RobotCommand_set_toBS(REM_RobotCommandPayload *remrcp, bool toBS){
    remrcp->payload[1] = ((toBS << 1) & 0b00000010) | (remrcp->payload[1] & 0b11111101);
}

static inline void REM_RobotCommand_set_toPC(REM_RobotCommandPayload *remrcp, bool toPC){
    remrcp->payload[1] = (toPC & 0b00000001) | (remrcp->payload[1] & 0b11111110);
}

static inline void REM_RobotCommand_set_fromRobotId(REM_RobotCommandPayload *remrcp, uint32_t fromRobotId){
    remrcp->payload[2] = ((fromRobotId << 4) & 0b11110000) | (remrcp->payload[2] & 0b00001111);
}

static inline void REM_RobotCommand_set_fromColor(REM_RobotCommandPayload *remrcp, bool fromColor){
    remrcp->payload[2] = ((fromColor << 3) & 0b00001000) | (remrcp->payload[2] & 0b11110111);
}

static inline void REM_RobotCommand_set_reserved(REM_RobotCommandPayload *remrcp, bool reserved){
    remrcp->payload[2] = ((reserved << 2) & 0b00000100) | (remrcp->payload[2] & 0b11111011);
}

static inline void REM_RobotCommand_set_fromBS(REM_RobotCommandPayload *remrcp, bool fromBS){
    remrcp->payload[2] = ((fromBS << 1) & 0b00000010) | (remrcp->payload[2] & 0b11111101);
}

static inline void REM_RobotCommand_set_fromPC(REM_RobotCommandPayload *remrcp, bool fromPC){
    remrcp->payload[2] = (fromPC & 0b00000001) | (remrcp->payload[2] & 0b11111110);
}

static inline void REM_RobotCommand_set_remVersion(REM_RobotCommandPayload *remrcp, uint32_t remVersion){
    remrcp->payload[3] = ((remVersion << 4) & 0b11110000) | (remrcp->payload[3] & 0b00001111);
}

static inline void REM_RobotCommand_set_messageId(REM_RobotCommandPayload *remrcp, uint32_t messageId){
    remrcp->payload[3] = (messageId & 0b00001111) | (remrcp->payload[3] & 0b11110000);
}

static inline void REM_RobotCommand_set_timestamp(REM_RobotCommandPayload *remrcp, uint64_t timestamp){
    remrcp->payload[4] = (timestamp >> 40);
    remrcp->payload[5] = (timestamp >> 32);
    remrcp->payload[6] = (timestamp >> 24);
    remrcp->payload[7] = (timestamp >> 16);
    remrcp->payload[8] = (timestamp >> 8);
    remrcp->payload[9] = timestamp;
}

static inline void REM_RobotCommand_set_payloadSize(REM_RobotCommandPayload *remrcp, uint32_t payloadSize){
    remrcp->payload[10] = payloadSize;
}

static inline void REM_RobotCommand_set_rho(REM_RobotCommandPayload *remrcp, float rho){
    uint32_t _rho = (uint32_t)(rho / 0.0004577706569009F);
    remrcp->payload[11] = (_rho >> 8);
    remrcp->payload[12] = _rho;
}

static inline void REM_RobotCommand_set_theta(REM_RobotCommandPayload *remrcp, float theta){
    uint32_t _theta = (uint32_t)((theta +3.1415926535897931F) / 0.0000958752621833F);
    remrcp->payload[13] = (_theta >> 8);
    remrcp->payload[14] = _theta;
}

static inline void REM_RobotCommand_set_yaw(REM_RobotCommandPayload *remrcp, float yaw){
    uint32_t _yaw = (uint32_t)((yaw +3.1415926535897931F) / 0.0000958752621833F);
    remrcp->payload[15] = (_yaw >> 8);
    remrcp->payload[16] = _yaw;
}

static inline void REM_RobotCommand_set_angularVelocity(REM_RobotCommandPayload *remrcp, float angularVelocity){
    uint32_t _angularVelocity = (uint32_t)((angularVelocity +31.4159265358979312F) / 0.0009587526218325F);
    remrcp->payload[17] = (_angularVelocity >> 8);
    remrcp->payload[18] = _angularVelocity;
}

static inline void REM_RobotCommand_set_cameraYaw(REM_RobotCommandPayload *remrcp, float cameraYaw){
    uint32_t _cameraYaw = (uint32_t)((cameraYaw +3.1415926535897931F) / 0.0000958752621833F);
    remrcp->payload[19] = (_cameraYaw >> 8);
    remrcp->payload[20] = _cameraYaw;
}

static inline void REM_RobotCommand_set_dribbler(REM_RobotCommandPayload *remrcp, float dribbler){
    uint32_t _dribbler = (uint32_t)(dribbler / 0.0039215686274510F);
    remrcp->payload[21] = _dribbler;
}

static inline void REM_RobotCommand_set_kickChipPower(REM_RobotCommandPayload *remrcp, float kickChipPower){
    uint32_t _kickChipPower = (uint32_t)(kickChipPower / 0.0254901960784314F);
    remrcp->payload[22] = _kickChipPower;
}

static inline void REM_RobotCommand_set_doKick(REM_RobotCommandPayload *remrcp, bool doKick){
    remrcp->payload[23] = ((doKick << 7) & 0b10000000) | (remrcp->payload[23] & 0b01111111);
}

static inline void REM_RobotCommand_set_doChip(REM_RobotCommandPayload *remrcp, bool doChip){
    remrcp->payload[23] = ((doChip << 6) & 0b01000000) | (remrcp->payload[23] & 0b10111111);
}

static inline void REM_RobotCommand_set_kickAtYaw(REM_RobotCommandPayload *remrcp, bool kickAtYaw){
    remrcp->payload[23] = ((kickAtYaw << 5) & 0b00100000) | (remrcp->payload[23] & 0b11011111);
}

static inline void REM_RobotCommand_set_doForce(REM_RobotCommandPayload *remrcp, bool doForce){
    remrcp->payload[23] = ((doForce << 4) & 0b00010000) | (remrcp->payload[23] & 0b11101111);
}

static inline void REM_RobotCommand_set_useCameraAngle(REM_RobotCommandPayload *remrcp, bool useCameraAngle){
    remrcp->payload[23] = ((useCameraAngle << 3) & 0b00001000) | (remrcp->payload[23] & 0b11110111);
}

static inline void REM_RobotCommand_set_useYaw(REM_RobotCommandPayload *remrcp, bool useYaw){
    remrcp->payload[23] = ((useYaw << 2) & 0b00000100) | (remrcp->payload[23] & 0b11111011);
}

static inline void REM_RobotCommand_set_wheelsOff(REM_RobotCommandPayload *remrcp, bool wheelsOff){
    remrcp->payload[23] = ((wheelsOff << 1) & 0b00000010) | (remrcp->payload[23] & 0b11111101);
}

static inline void REM_RobotCommand_set_feedback(REM_RobotCommandPayload *remrcp, bool feedback){
    remrcp->payload[23] = (feedback & 0b00000001) | (remrcp->payload[23] & 0b11111110);
}

static inline void REM_RobotCommand_set_reboot(REM_RobotCommandPayload *remrcp, bool reboot){
    remrcp->payload[24] = ((reboot << 7) & 0b10000000) | (remrcp->payload[24] & 0b01111111);
}

// ================================ ENCODE ================================
static inline void encodeREM_RobotCommand(REM_RobotCommandPayload *remrcp, REM_RobotCommand *remrc){
    REM_RobotCommand_set_packetType          (remrcp, remrc->packetType);
    REM_RobotCommand_set_toRobotId           (remrcp, remrc->toRobotId);
    REM_RobotCommand_set_toColor             (remrcp, remrc->toColor);
    REM_RobotCommand_set_toBC                (remrcp, remrc->toBC);
    REM_RobotCommand_set_toBS                (remrcp, remrc->toBS);
    REM_RobotCommand_set_toPC                (remrcp, remrc->toPC);
    REM_RobotCommand_set_fromRobotId         (remrcp, remrc->fromRobotId);
    REM_RobotCommand_set_fromColor           (remrcp, remrc->fromColor);
    REM_RobotCommand_set_reserved            (remrcp, remrc->reserved);
    REM_RobotCommand_set_fromBS              (remrcp, remrc->fromBS);
    REM_RobotCommand_set_fromPC              (remrcp, remrc->fromPC);
    REM_RobotCommand_set_remVersion          (remrcp, remrc->remVersion);
    REM_RobotCommand_set_messageId           (remrcp, remrc->messageId);
    REM_RobotCommand_set_timestamp           (remrcp, remrc->timestamp);
    REM_RobotCommand_set_payloadSize         (remrcp, remrc->payloadSize);
    REM_RobotCommand_set_rho                 (remrcp, remrc->rho);
    REM_RobotCommand_set_theta               (remrcp, remrc->theta);
    REM_RobotCommand_set_yaw                 (remrcp, remrc->yaw);
    REM_RobotCommand_set_angularVelocity     (remrcp, remrc->angularVelocity);
    REM_RobotCommand_set_cameraYaw           (remrcp, remrc->cameraYaw);
    REM_RobotCommand_set_dribbler            (remrcp, remrc->dribbler);
    REM_RobotCommand_set_kickChipPower       (remrcp, remrc->kickChipPower);
    REM_RobotCommand_set_doKick              (remrcp, remrc->doKick);
    REM_RobotCommand_set_doChip              (remrcp, remrc->doChip);
    REM_RobotCommand_set_kickAtYaw           (remrcp, remrc->kickAtYaw);
    REM_RobotCommand_set_doForce             (remrcp, remrc->doForce);
    REM_RobotCommand_set_useCameraAngle      (remrcp, remrc->useCameraAngle);
    REM_RobotCommand_set_useYaw              (remrcp, remrc->useYaw);
    REM_RobotCommand_set_wheelsOff           (remrcp, remrc->wheelsOff);
    REM_RobotCommand_set_feedback            (remrcp, remrc->feedback);
    REM_RobotCommand_set_reboot              (remrcp, remrc->reboot);
}

// ================================ DECODE ================================
static inline void decodeREM_RobotCommand(REM_RobotCommand *remrc, REM_RobotCommandPayload *remrcp){
    remrc->packetType    = REM_RobotCommand_get_packetType(remrcp);
    remrc->toRobotId     = REM_RobotCommand_get_toRobotId(remrcp);
    remrc->toColor       = REM_RobotCommand_get_toColor(remrcp);
    remrc->toBC          = REM_RobotCommand_get_toBC(remrcp);
    remrc->toBS          = REM_RobotCommand_get_toBS(remrcp);
    remrc->toPC          = REM_RobotCommand_get_toPC(remrcp);
    remrc->fromRobotId   = REM_RobotCommand_get_fromRobotId(remrcp);
    remrc->fromColor     = REM_RobotCommand_get_fromColor(remrcp);
    remrc->reserved      = REM_RobotCommand_get_reserved(remrcp);
    remrc->fromBS        = REM_RobotCommand_get_fromBS(remrcp);
    remrc->fromPC        = REM_RobotCommand_get_fromPC(remrcp);
    remrc->remVersion    = REM_RobotCommand_get_remVersion(remrcp);
    remrc->messageId     = REM_RobotCommand_get_messageId(remrcp);
    remrc->timestamp     = REM_RobotCommand_get_timestamp(remrcp);
    remrc->payloadSize   = REM_RobotCommand_get_payloadSize(remrcp);
    remrc->rho           = REM_RobotCommand_get_rho(remrcp);
    remrc->theta         = REM_RobotCommand_get_theta(remrcp);
    remrc->yaw           = REM_RobotCommand_get_yaw(remrcp);
    remrc->angularVelocity= REM_RobotCommand_get_angularVelocity(remrcp);
    remrc->cameraYaw     = REM_RobotCommand_get_cameraYaw(remrcp);
    remrc->dribbler      = REM_RobotCommand_get_dribbler(remrcp);
    remrc->kickChipPower = REM_RobotCommand_get_kickChipPower(remrcp);
    remrc->doKick        = REM_RobotCommand_get_doKick(remrcp);
    remrc->doChip        = REM_RobotCommand_get_doChip(remrcp);
    remrc->kickAtYaw     = REM_RobotCommand_get_kickAtYaw(remrcp);
    remrc->doForce       = REM_RobotCommand_get_doForce(remrcp);
    remrc->useCameraAngle= REM_RobotCommand_get_useCameraAngle(remrcp);
    remrc->useYaw        = REM_RobotCommand_get_useYaw(remrcp);
    remrc->wheelsOff     = REM_RobotCommand_get_wheelsOff(remrcp);
    remrc->feedback      = REM_RobotCommand_get_feedback(remrcp);
    remrc->reboot        = REM_RobotCommand_get_reboot(remrcp);
}

#endif /*__REM_ROBOT_COMMAND_H*/
